### ISSUE TITLE
Upgrade Postgres 9.4 -> 11

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#1024]
- [x] [Spike to investigate what is required to upgrade to Postgres 11](https://github.com/hypothesis/product-backlog/issues/1026)
- [x] Update Python libraries in h that talk to the DB (psycopg, sqlalchemy) to current version
- [x] Switch Jenkins CI builds for lms and the client to use Postgres 11
- [x] Review plan for executing Postgres 11 upgrade
- [x] Upgrade RDS instances to Postgres 11 (https://docs.google.com/document/d/1dbwSiONiuLQ8Bq31fEpAFtflBpalsIzp0_hF-iWlY1o/edit)
- [x] Update analytics scripts to dump from new read replica
- [ ] Perform any cleanup tasks following the RDS upgrade (see [comment](https://github.com/hypothesis/product-backlog/issues/1024#issuecomment-554664105))
- [ ] Document how developers can upgrade their dev environments to PG 11

**Comment by seanh** [comment]
@dmfine I've changed this card into an epic that currently only has one task, a spike. The spike will identify more tasks, which we'll then add to the task list on this card

**Comment by dmfine** [comment]
Upgrade plan: https://docs.google.com/document/d/1dbwSiONiuLQ8Bq31fEpAFtflBpalsIzp0_hF-iWlY1o/edit

**Comment by robertknight** [comment]
Postgres 11 cleanup tasks:

- [x] Pause the old PG 9.4 instances
- [ ] Remove the old PG 9.4 instances after a couple of days
- [ ] Make sure nothing in the playbook references the old database instances
- [ ] Search for any references to Postgres 9.4 in other repos (lms, h) and adjust as necessary
- [ ] Review the "Notes from during the migration" section in the [Postgres 11 migration Google Doc](https://docs.google.com/document/d/1dbwSiONiuLQ8Bq31fEpAFtflBpalsIzp0_hF-iWlY1o/edit#heading=h.46816krldj4a) and follow up or schedule work to follow up on any actionable items.
- [ ] Update documentation for how to do a major Postgres version update, assuming future updates use the same procedure. Make sure this is linked to from the migration plan.

**Comment by robertknight** [comment]
I grepped for references to "postgres.*9" in the various H repos I have checked out locally (including h, lms, playbook). I found the following:

- In the h and lms repos, `docker-compose.yml` references Postgres 9.4. This is linked to figuring out the easiest path for devs to upgrade their local environments to PG 11
- In the h repo there are a couple of references to documentation pages from Postgres 9.x. These probably don't require any changes, since the existing tests all passed.
- In the playbook repo:
  - There is an Ansible playbook which I believe was used to create the original Postgres DB, but no longer matches the running infrastructure. See `bootstrap/roles/rds/tasks/postgres.yml`
  - `configure/roles/postgresql/tasks/postgresql.yml` references Postgres 9.3 (!)
