### ISSUE TITLE
(EPIC) Implementation of the client work for Publisher Groups (does not include moderation or customization) 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#104]
There are changes that need to be made to the client in order to implement publisher groups. 

Some of these changes include the third party token handling between the API and the client, the triggering of the sidebar from the publisher's page, and the UI changes that will need to be made in order to ship publisher groups. 

### Issues in this epic: 
- [x] (SPIKE) Research how to trigger opening of sidebar from an arbitrary link #38 
- [x] (SPIKE) Research Implementation of the "Client third party auth thing (official name)" #66 
- [x] (SPIKE) Research implementation of publisher group mode for the client #64 
- [x] Add annotation counts to scope control #67
