### ISSUE TITLE
Implement pagefit solution for PDFs

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1046]
## User story
As a student annotating PDFs, I want to view the contents of the annotation sidebar and my source text at the same time.

## Background
A long-standing feature request is https://github.com/hypothesis/product-backlog/issues/94, "Don't cover the page with your sidebar."

@judell came up with a proof of concept that has been working reliably; it's a lot simpler to implement for PDFs first because every page rendered by PDF.js with our annotation overlay has exactly the same structure. 

This issue is to plan work for implementing pagefit for PDFs. We can close out #94 when a fix for HTML is implemented. 

The desired experience:
- [x] When the sidebar is open, it does not cover the PDF
- [x] The sidebar does not automatically close when I click on the document
- [x] On small screens, or at small widths, the sidebar may have to cover the PDF so the PDF remains readable

**Comment by robertknight** [comment]
I think it is useful here to look at how the current version of PDF.js handles this issue for the table of contents/thumbnails view that opens from the left. There is some subtlety involved in balancing the desire to:

- Avoid having the side panel cover up the text
- Keep the text of the document readable

When Automatic Zoom is enabled, which is the default, the thumbnails panel seems to have the following behavior:

- When the screen is wide enough, opening the thumbnail panel will not resize the document at all, but reduce the amount of margin on either size of the document and shift the content over to keep the document centered
- When the screen is narrower, so that there isn't space for the thumbnail panel and the content, opening the thumbnail panel resizes the content
- When the screen is narrower still, after some threshold is reached, opening the thumbnail panel no longer resizes the content but instead the thumbnail panel slides over the document with a semi-transparent background, so the text can be read through it

When we come to implement this, we've got a feature-flagging mechanism available in Via now so we could just take Jon's prototype pretty much as is and land that behind a flag as a first pass. @judell can you add a note here with a pointer to your changes?

**Comment by judell** [comment]
@Robert Knight <robertknight@hypothes.is> will do.

**Comment by judell** [comment]
https://github.com/hypothesis/client/compare/master...judell:pdf-pagefit

**Comment by mkdir-washington-edu** [comment]
Tickets:
https://hypothesis.zendesk.com/agent/tickets/8233
https://hypothesis.zendesk.com/agent/tickets/8260
https://hypothesis.zendesk.com/agent/tickets/8500
https://hypothesis.zendesk.com/agent/tickets/10202
https://hypothesis.zendesk.com/agent/tickets/10630 - User suggests we left-align instead of center-align PDFs when LMS assignments are opened in a new tab.

**Comment by judell** [comment]
Feedback from a user of an experimental build with this feature included:

> Your experimental build is almost a dream come true!

 > First of all, now we can for real use Hypothes.is with PDF, thanks to the text moving to the left side of the screen. I missed this feature so sorely that I did annotation sessions with my students on PDFs in Google Drive.

**Comment by judell** [comment]
This video compares stock Hypothesis on the left to the variant in the above-linked branch. 
Using the latter yesterday, I noticed that it's really annoying to have the sidebar shut every time I make a selection. This isn't an introduced behavior, it's something the client always does. But if you've got the annotated page and the sidebar in a tiled side-by-side arrangement, it wouldn't be necessary, right?

https://jonudell.info/h/sidebar-shuts-on-selection.mp4

**Comment by franzau** [comment]
agree, it would be better to have the text stable on the left side. The sidebar could stay open by default, at least if it does not overlap the text. My problem, however, it is the text moving to the middle of the screen when the sidebar shuts.

**Comment by seanh** [comment]
_On small screens, or at small widths, the sidebar may have to cover the PDF so the PDF remains readable_ <- This will apply in LMS

**Comment by robertknight** [comment]
We discussed this on a sprint planning call just now. One of the things I think we should try to identify in this coming sprint is should we:

1. Always shrink/shift the page when the sidebar is open
2. Shrink/shift it conditionally using some smart logic (ala. [the comment above](https://github.com/hypothesis/product-backlog/issues/1046#issuecomment-530798369))
3. Provide some kind of control or preference within the application to adjust the behaviour

As I mentioned in the comment above, we could land a minimal version based on Jon's prototype behind a feature flag initially if we want to give more people internally a chance to try this while we're figuring this out.

**Comment by judell** [comment]
See Slack discussion here, https://hypothes-is.slack.com/archives/C2BLQDKHA/p1593012739226700: 

> A user was asking why the Sidebar closes when you select text on the page. I thought the reason for this would be to move the Sidebar out of the way while selecting so it doesn’t cover text, but it seems like the Sidebar only retracts when you finish selecting text, not when you start.

This is what I'm referring to above.

**Comment by lyzadanger** [comment]
@judell I was doing a little bit of information-gathering on this project. The branch you referenced on your fork of the client (`pdf-pagefit`) in [this comment](https://github.com/hypothesis/product-backlog/issues/1046#issuecomment-531820881) doesn't appear to exist anymore, even if I dig through GitHub's archive of older branches. Do you have that POC work somewhere accessible? Thanks!
