### ISSUE TITLE
Upgrade to PDF.js v2.x

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#1062]
Our current PDF annotation tools currently use versions of PDF.js v1.x from 2015. Since then there have been 4 years worth of work done upstream to improve performance, compatibility, text handling etc.

This issue is an epic covering the work involved in upgrading all of our PDF annotation environments to PDF.js v2.x. This work should also include making it easier to perform future PDF.js updates.

Sub-tasks:

- [x] Create tools to compare anchoring results on a real sample of PDFs with PDF.js v1 and PDF.js v2 (https://github.com/hypothesis/anchoring-test-tools)
- [x] Upgrade Via to PDF.js v2 https://github.com/hypothesis/via/issues/81
- [x] Remove feature flag to downgrade to PDF.js v1 for a specific Via request (https://github.com/hypothesis/via/pull/185)
- [x] Upgrade the Chrome extension to PDF.js v2 (https://github.com/hypothesis/browser-extension/issues/222) (https://github.com/hypothesis/browser-extension/pull/255)
- [ ] Upgrade our pre-packaged viewer (https://github.com/hypothesis/pdf.js-hypothes.is) to PDF.js v2 (https://github.com/hypothesis/pdf.js-hypothes.is/issues/15) (https://github.com/hypothesis/pdf.js-hypothes.is/pull/17, https://github.com/hypothesis/pdf.js-hypothes.is/pull/16)

**Comment by dwhly** [comment]
> Upgrade our pre-packaged viewer

Request that this be bumped underneath the Chrome extension upgrade as the next priority.

**Comment by klemay** [comment]
@robertknight since https://github.com/hypothesis/browser-extension/issues/222 and https://github.com/hypothesis/pdf.js-hypothes.is/issues/15 are completed/closed, does that mean this issue can be closed too?

**Comment by robertknight** [comment]
Yes, indeed!
