### ISSUE TITLE
EPIC: Follow-up items from accessibility audit

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1112]
We had what we hoped would be our final accessibility audit this week, and a few items remain outstanding. A few of these items are straightforward and can be taken care of in this sprint:

- [x] [Remove “select” and “tab” from tab labels #1107 ](https://github.com/hypothesis/product-backlog/issues/1107)
- [x] [Use 'aria-expanded' attribute to label buttons that show and hide panels #1110 ](https://github.com/hypothesis/product-backlog/issues/1110)

And the remaining items raise some questions for us:

- [x] [Number of annotations imperceptible by ATs #1108 ](https://github.com/hypothesis/product-backlog/issues/1108)
- [x] [Get clarity on A11y question regarding "More" toggle #1109](https://github.com/hypothesis/product-backlog/issues/1109)
- [x] [A11y question re: consistent screenreader experience for toggles #1111 ](https://github.com/hypothesis/product-backlog/issues/1111)

My understanding: 

- We can address #1108 if we get some guidance re: what the implementation would look like. 
- Issues #1109 and #1111 may end up being usability issues that get prioritized in our backlog
