### ISSUE TITLE
Consider changing our documentation tools and practices

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/product-backlog#1123]
## Background

I think there are some missing characteristics from our documentation solutions that can't be fixed in the individual tools we use. At the moment it's hard to articulate those exact issues for lack of an example. As a very quick stab at those, I'd say they revolve around:

 * Effort barriers that render tools ineffective
 * A lack of intra-document linking (table of contents, easy jump to section)
 * A lack of inter-document linking (in a maintainable way)
 * Separate documents as separate spaces (a PDF, ticket or page being it's own little world)
 * Inability to provide contextual content (things before, after, around)
 * Poor support for mixed mode content (text, images, videos, spreadsheets in the same place)

My original plan was to create a demo instance of Confluence with examples of various different types of documentation imported and interlinked to demonstrate the benefits of an integrated product.

This original plan may have morphed somewhat now into a general options assessment.

## Current requirements

Arti provided a list of requirements, but their meaning and origin is a bit murky to me. I don't think this list reflects the problems I'm seeing, and I suspect there may be some "problems beneath the requirements" here. I'd like to ask "why" a few times for each of these to see if we can get to the deeper reasons.

For example "Preference for smaller/independent companies" does not seem to mirror our existing stack (Amazon, Microsoft, Google, Cloudflare etc.). Or "Doesn't need to have all the bells and whistles", is this saying we have a preference for tools in which you _can't_ do things? It would be good to get under those and find out why and what they mean.

If these requirements are adding up to ruling in or out a particular solution (i.e. I don't like product X, but I do like product Y, but don't want to say so directly) it's going to be easier to have an honest conversation if we can make preferences explicit.

## What to do

 * [ ] Get sign off on this idea, try and get some bounds for scope (smaller = better)
 * [ ] Codify and explain what I think we're missing - Produce something people can read and consider
 * [ ] See if there is appetite to create a visual demo in a product (probably Confluence if I'm doing it) to make it concrete
 * [ ] Interview people about the list of requirements below to try and work back to problems they are trying to solve
 * [ ] Come up with a list of high quality _problems_ we are trying to solve, from which requirements should be derived
 * [ ] Organise our requirements as children of problems
 * [ ] Evaluate various products against those requirements (including status-quo products)

----

Requirements from @ajpeddakotla 

Wiki requirements:

- Preference for being able to write in Markdown
- Good indexing
- Deep search features
- Doesn't box us in to product - meaning, if we ever make the decision to leave the product, will we lose all of our data?
- Is something the technical and non-technical teams can use
- Doesn't need to have all the bells and whistles - a good text editor/writing feature, indexing and searching.
- Allow for import of data from other sources.
- Preference for smaller/independent companies.
- Since we'd be adding another tool, we need to also think of cost and try and keep costs down. 

Possible options:

- Confulence: https://www.atlassian.com/software/confluence
- Tettra: https://tettra.com/
- Nuclino: https://www.nuclino.com/
- Notion: https://www.notion.so/
- Basecamp: https://basecamp.com/
- Slab: https://slab.com/
- There's also this wiki alternative: Guru https://www.getguru.com/

**Comment by lyzadanger** [comment]
PEANUT GALLERY COMMENT COMING UP: Really dislike Basecamp's editor (have used much, and recently tried to use BC for organizing a community event).

**Comment by dwhly** [comment]
Here's a philosophical data point:

A few years back we were evaluating knowledge base solutions-- i.e. a store of knowledge about the product and service that tends to surface and be needed within a customer support context.  For us, our kb started early on as a FAQ and then became more.  We soon outgrew our clumsy FAQ page.  

Zendesk had a KB offering, and it was one of the solutions that we looked at-- it integrated with ZD of course, which we were using.  The only problem is that the host for this knowledge was zendesk, and they didn't even allow vanity URLs, so it would have been something like hypothesis.zendesk.com.  As we built this critical store of knowledge and customers linked into it and referenced it, those zendesk URLs would begin to be embedded everywhere. Makes it hard to switch!

My objection then of course was that for many services there are high switching costs, but that fundamentally most are self-contained and "away from the customer or end user".  It may be painful to switch, but once you do it's done, and the customer never knows any different. It feels like end-user facing knowledge systems that can be linked to from the outside world fall in a special category of their own because changing a service provider might be quite disruptive.

On the KB side, we found an excellent WP plugin, Heroic, that was a much lower fee and where we host the pages exclusively within our existing WP site, in our database, on URLs we determine, and where we have complete design control.  This means as far as we can tell, we'll never have to change our links unless we completely rearchitect the way we do KB.  (For example: https://web.hypothes.is/help/lms-app-canvas/ feels like a relatively stable URL).

It feels like our developer documentation falls in a similar category.  Namely, something that's more intimately connected with our code and our institutional knowledge that we don't want to be rented back to us by a service provider using a proprietary system-- even if they're willing to deliver it via a subhost on our domain.

As we evaluate solutions can we track and consider how they compare on these dimensions as well?  A quick search for "Wordpress documentation plugins" turns up a bunch of promising options, but perhaps there are other avenues to explore as well.

**Comment by dwhly** [comment]
> Preference for smaller/independent companies

I'm not sure I agree w/ this one.  I think we have a preference for high quality solutions that look like the code base or service isn't disappearing anytime soon.  We want something likely to be around in 10 years and probably 20.  A smaller / independent company might provide this, but a larger one could too.  I'm very happy we're on (self-hosted) Wordpress for our website for instance.  Not likely to go away anytime soon.

**Comment by akuckartz** [comment]
Please use Open Source. And please consider [Semantic MediaWiki](https://www.semantic-mediawiki.org/).

**Comment by dwhly** [comment]
> Please use Open Source

I'd definitely add this as a factor in our comparison matrix.

**Comment by jon-betts** [comment]
Honestly I think this whole conversation has moved some distance from where I initially envisaged it, which was:

* I think there's a gap
* As it's not something we have, we don't rely on it
* So it's not perceived of as a gap
* So our solutions all consist of remixing things we have
* The gap remains

As it's very hard to get people to see why it might be beneficial to add a capability, I think a demo that lets them see would help and ground the conversation.

My idea was to get a free demo of a product I'm familiar with, put multi-modal documentation, reports, sketches, FAQ's etc in there to show the benefits of having something which puts them all in one place, and in the context of each other. My hope was that people would say "I think I see what you're talking about" rather than "let's use that product".

My concern with listing a series of product right now is I don't think I've got to the point of explaining what I think is missing. I worry it's premature to talk about evaluate products, if we have yet to agree on what (if any) problems we are trying to solve with them.

I don't think we have a burning need to get a new product, for which we should brainstorm reasons this would be a good idea. I think we have specific problems which I think we should flesh out first, before even considering if we need a new product.
