### ISSUE TITLE
EPIC: Handle Canvas authorization errors more gracefully 

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1134]
## Summary

Students using our Canvas application sometimes get caught in a loop where they are asked to repeatedly authorize Hypothesis. The support team has identified 5 common issues that lead to this auth loop happening. We should look into whether there is a way to handle these issues more gracefully. **The desired outcome is making Canvas authorization errors easier for our support team to diagnose by showing more information to the user re: why authorization is failing.**

## Details

The first time a student launches a Canvas assignment created with a Canvas PDF, they are asked to authorize Hypothesis: 

![image](https://user-images.githubusercontent.com/12087705/91204448-1bac0380-e6d2-11ea-8689-577571fb288e.png)

Usually, the student clicks "authorize" and then the assignment loads normally for them. Sometimes, instead, students are led to this screen:

![image](https://user-images.githubusercontent.com/12087705/91204541-3ed6b300-e6d2-11ea-8075-69b9bc3a7567.png)

Clicking "Authorize" leads back to the first screenshot, and the student is caught in a loop. 

## Reasons this may happen and how users fix it

- [x] **The student’s browser is old, or is not compatible (like IE and legacy Edge)**: To fix this, the student launches the assignment with the latest version of Firefox or Chrome. Fixed by https://github.com/hypothesis/product-backlog/issues/1141
- [x] **The instructor hasn’t Published the document in Canvas Files**: To fix this, the instructor changes the settings of the file in Canvas. Fixed by https://github.com/hypothesis/lms/issues/2217
- [ ] **There’s an error in the installation (for example, the Canvas Admin never turned on the Dev Key)**: To fix this, an LMS administrator reviews the app installation for errors and if necessary, uninstalls and reinstalls our app
- [ ] **There are multiple installs of the Hypothesis LMS app in Canvas, and Canvas has launched the wrong install**: To fix this, an LMS admin removes one of the app installs. We have an open issue to see if we can address this on our end: https://github.com/hypothesis/lms/issues/915
- [x] **The instructor has used Canvas’ course copy function**: To fix this, the instructor must edit the Assignment, re-add Hypothesis as the external tool, and select the document again. Fixed by https://github.com/hypothesis/lms/issues/2217

As explained in [lms/#915](https://github.com/hypothesis/lms/issues/915), there's likely not much we can do about Reason 4 without work on Canvas' end to make this a smoother experience. 

Reason 5 may be mitigated with [lms/#555](https://github.com/hypothesis/lms/issues/555), as supporting course copy would allow those assignments to work properly. 

Seems like reasonable next steps would be:

- Address reason 1 by warning students when they launch us with an outdated/incompatible browser
- Address reason 2 by showing a warning that the file associated with the assignment isn't available and instruct students to ask profs to make sure the file is published 
- Address reason 3 by building error messages for common failure points with app installs (i.e., "we expected to receive a developer key and did not")

I can write up 1 & 2 as Github issues if developers agree that these are reasonable; for 3 we'll need a list of failure points from support so we can write up individual issues.

**Comment by mkdir-washington-edu** [comment]
Per our discussion today, I was asked to give which of the 5 causes I think is the most frequent for Devs. I think the most frequent cause is #1, the student browser error. The hardest to diagnose is #4, when there are multiple Hypothesis installs in the course. Either would be helpful, so whichever is easier to implement would be great.
