### ISSUE TITLE
Customers sometimes get "pure" VitalSource

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1257]
Per [this discussion in Slack](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1637263484304600).

The different flows one can take into the assignment after landing on vitalsource are:

- Opt out of all cookies (which should kick you out and put you into a loop)
- Accept cookies, then,
  - Bypass the login (already logged in)
  - Skip this step
  - Sign in (existing account)
  - Sign in with email only??? (in the video it seems like they weren't prompted for signup?)
  - Sign up (new account)

You could do these

- As a teacher, after creating an assignment
- As a student in the course

If we don't have a sense of what's causing this, we may need to just run through these scenarios and see if we can reproduce.

Questions

- [x] Could it be that their own school canvas logins were still active and those schools don't have VitalSource enabled? (See #1250 )
- [x] Do we need to ask VitalSource about this? How does authentication with them work?
- [x] Can support run through these scenarios?
- [x] One candidate seems to be Safari. Could we run through that, given I don't have a Safari (do we have a LambdaTest or something similar I could play with?)

## Todo

- [ ] Chris: Ask Michael to run through scenarios above
  - [ ] Try in Safari vs Chrome
- [ ] Chris: Email Kimberly to set up debug
  - [ ] See what happens when she's logged in to both canvas instances
- [ ] Robert: provide request we should see

## Notes

- First we need to confirm that correct Hypothesis-branded version of VS is being loaded, not the pure VS.
- After they log in, is the code loading?
  - Look in network requests to see if it's being requested
- Or is it's there but it's breaking?

**Comment by chrisshaw** [comment]
This was due to changes made by VitalSource at the time. We don't see it anymore.
