### ISSUE TITLE
Partial Results Update - Start the fetch

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#134]
**Summary:**
Use ajax to update the search results live while the user is interacting or finishing with adding lozenges.
[Spike ticket where research work on this issue was documented](https://github.com/hypothesis/h/issues/4219)

**Task to be completed:** 
- [ ] create/delete lozenge and create an event to indicate a fetch request has been made
- [ ] listen to update results event and update the groups and tags lists
- [ ] listen to update results event to get the form action and update the form thats bound to the search bar
