### ISSUE TITLE
Partial Results Update - Respond to the fetch

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#135]
**Summary:**
Use ajax to update the search results live while the user is interacting or finishing with adding lozenges.
[Spike ticket where research work on this issue was documented](https://github.com/hypothesis/h/issues/4219)

**Task to be completed:** 
- [ ] create a search-results controller
- [ ] listen for the fetch request start event and apply a class that increases the search results container opacity
- [ ] listening for the update results event and calling reload on itself with the new content - See: this.options.reload(elem, html) and remove the opacity class.
- [ ] Handle the race condition where multiple fetches can be requested and we only need to handle the latest fetch.
