### ISSUE TITLE
Ohio keyboard shortcuts

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/product-backlog#1374]
We have a contractual commitment to meet some demands for Ohio State University. The release date for these items is end of Q3 - which means we need to coordinate this release early enough to get time in for testing. These are related to 5 key items listed below:

- [x] Keyboard shortcuts for highlighting and annotating are not conveyed to the user via instruction. (https://github.com/hypothesis/client/issues/4742)
- [x] When users are using the screen reader to read through a document, they are told an annotation exists when passing over one. However, they cannot jump to the annotation and read it. It is worth noting here that using the annotation pane to read annotations enables users to jump to the point in the document that was annotated. (https://github.com/hypothesis/client/issues/4741)
- [x] When reading annotations in the annotation frame, the user has to go backwards through the DOM to get to the search function. (https://github.com/hypothesis/client/issues/4739)
- [ ] On screen readers other than VoiceOver, the A and H keys for annotating and highlighting respectively do not work without entering passthrough mode. This is not an ideal user experience and not obvious to the screen reader users. (https://github.com/hypothesis/client/issues/4738)
- [x] On heavily annotated documents, the start and end annotation messages can make the reading experience very strange and unusable. There is a way to turn off annotations that solves this problem...however, that function should utilize a keyboard command as well so users can enable it on the fly. (https://github.com/hypothesis/client/issues/4740)

For further information on this ticket please reference this document where Rob and Lyza have commented on possible solutions/thoughts:
https://docs.google.com/document/d/1lwXKp8pRX1DyuhTblsGNQP8hnWhyVdVr/edit

**Comment by darylhedley** [comment]
There are questions around whether we should (or are going to via a side effect) tackle these two other outstanding items from a previous ticket:

2.1.1-keyboard-access. While I can access the hypothesis content using the keyboard, I had to tab through the entire webpage before accessing the hypothesis content. Cannot annotate using keyboard only. Cannot access annotations within content page using only keyboard. Voiceover on mac does recognize where an annotation is, but cannot access it.
2.4.1-bypass-function. No method is provided to bypass repetitive content.

**Comment by mattdricker** [comment]
> On screen readers other than VoiceOver, the A and H keys for annotating and highlighting respectively do not work without entering passthrough mode. This is not an ideal user experience and not obvious to the screen reader users

Important to note that this ^ is not an issue specific to Hypothesis, but to any web app requiring text selection. Solving this is dependent on completion of upstream work currently in process:

- We've partnered with Mick Curran at NVDA, who shepherded in a change to the  IAccessible2 framework providing for a new text selection container
- Next step is code changes to Chromium and Firefox to recognize this. Last update these are still in flight.
- Then NVDA and JAWS have committed to make the necessary changes in their code

Once all the above is done, we may actually not need to do anything in our code. It should "just work" as it does currently in VoiceOver.

**Comment by lyzadanger** [comment]
> There are questions around whether we should (or are going to via a side effect) tackle these two other outstanding items from a previous ticket:
> 
> 2.1.1-keyboard-access. While I can access the hypothesis content using the keyboard, I had to tab through the entire webpage before accessing the hypothesis content. Cannot annotate using keyboard only. Cannot access annotations within content page using only keyboard. Voiceover on mac does recognize where an annotation is, but cannot access it. 2.4.1-bypass-function. No method is provided to bypass repetitive content.

@darylhedley So...are these requirements for this project?

**Comment by robertknight** [comment]
I added links to the description with the improvements that we have made so far.
