### ISSUE TITLE
Support annotating YouTube video transcripts

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#1433]
This is the tracking issue for our first foray into video annotation. See the [product document in Notion](https://www.notion.so/Video-Annotations-04a47da12eca42b8998be93953a243af) for additional background and scope details. 

## Useful internal links

- [Product doc and design sketches](https://www.notion.so/Video-Annotations-04a47da12eca42b8998be93953a243af)
- Project board: https://github.com/orgs/hypothesis/projects/118/
- Internal Slack: `#project-video-annotations`

- Interactive UI mock: https://hypothesis-video-transcriptions.netlify.app

## Related issues

Previous issues relating to annotation of videos: https://github.com/hypothesis/product-backlog/issues/1098, https://github.com/hypothesis/product-backlog/issues/1142, https://github.com/hypothesis/product-backlog/issues/1298.

## Summary

We are going to add the ability for instructors in the LMS to create Hypothesis assignments using a YouTube video link. These assignments will launch a player that displays the video alongside a transcript of the video. Users will be able to annotate, highlight and discuss passages from the transcript. This feature is envisioned as an evolved form of the YouTube transcript annotation in https://docdrop.org.

Supporting use in the LMS is the main priority, but it would be useful for this capability to be available to regular Hypothesis users as well. We might run into some additional challenges with this that lead us to deploy that later ([discussion thread](https://hypothes-is.slack.com/archives/C054CG5PH5M/p1682508117869989)).

## Sub-components

- [ ] Add option to use a YouTube link as an assignment source in the LMS app (https://github.com/hypothesis/lms/issues/5328)
- [ ] Add backend API in the LMS app to support the selection UI
- [ ] Revise initial step of content selection UI in LMS so that users don't miss the YouTube option if it doesn't fit on the screen
- [ ] Add a video player frontend app to Via which displays a YouTube video, transcript and Hypothesis client (https://github.com/hypothesis/via/issues/904)
- [ ] Add backend infrastructure in Via to support fetching transcripts for videos, caching them, and exposing them to the frontend
- [ ] Capture appropriate metadata (URL, timestamps, video metadata etc.) with annotations that are made on YouTube videos (https://github.com/hypothesis/via/issues/941)

**Comment by lyzadanger** [comment]
> Revise initial step of content selection UI in LMS so that users don't miss the YouTube option if it doesn't fit on the screen

See also https://github.com/hypothesis/lms/issues/2955

I'd love to have a real, pressing excuse to get this work done.

**Comment by robertknight** [comment]
This is what the content picker's initial screen looks like in most existing Canvas installations:

<img width="827" alt="LMS content picker" src="https://user-images.githubusercontent.com/2458/234574464-4c30b109-d5bd-4a60-8b43-8bd8ee67050e.png">

There isn't room for a whole new button there, although part of one will fit, to at least indicate the user can scroll. Here I have made the picker just a little smaller than that manually, to show what it would look like if the viewport happens to be a size where a whole number of buttons fit, but some are hidden off the bottom:

<img width="788" alt="LMS picker small" src="https://user-images.githubusercontent.com/2458/234574895-5ed2dfca-a0d3-4870-ab5d-729dd5945e8f.png">

In this case it might not be obvious to users that there are additional options they can see by scrolling.

**Comment by lyzadanger** [comment]
> There isn't room for a whole new button there, although part of one will fit, to at least indicate the user can scroll. Here I have made the picker just a little smaller than that manually, to show what it would look like if the viewport happens to be a size where a whole number of buttons fit, but some are hidden off the bottom

Another quickish option might be to establish a CSS grid with two columns of buttons.

**Comment by acelaya** [comment]
> Another quickish option might be to establish a CSS grid with two columns of buttons.

Dan suggested this option too

**Comment by dwhly** [comment]
Added some thoughts on this to the other ticket: https://github.com/hypothesis/lms/issues/2955.  For sure, in the short term it might be expedient to just move to two columns!

**Comment by dwhly** [comment]
@jaredpdesigns has done a quick CSS implementation of the [figma design](https://www.figma.com/file/fnE3zn2abgWaDtPQO9mQ51/Hypothesis---Video-Annotations?node-id=0-1&t=AhUP0P64kpkN8hIt-0).  Here: https://hypothesis-video-transcriptions.netlify.app/   It should note that this implementation takes advantage of @robertknight's work to implement HTML "side-by-side", so that when the H client sidebar is expanded, it squeezes the content frame accordingly.  This works now if you have the feature flag for this implementation enabled in your H profile.  This work was discussed in the #design channel here: https://hypothes-is.slack.com/archives/C07NXBDNW/p1681675149376879

**Comment by Facni** [comment]
For normal users. Why it cannot be like glasp? 
Example:
![imagen](https://github.com/hypothesis/product-backlog/assets/112446096/4de1548c-32f5-41fa-835d-dd18bfe1e9a7)

**Comment by robertknight** [comment]
This feature was fully implemented last year, but this issue stopped getting updated at some point.
