### ISSUE TITLE
Automatic email campaigns in Hubspot

### ISSUE THREAD

**Issue by leedenison** [hypothesis/product-backlog#1460]
Replaces:

 * https://github.com/hypothesis/report/issues/212

[PRD: Automated Email Outreach User List Generation](https://docs.google.com/document/d/1tRVRO6vkHjcPDn9H3WmlvcU4OyjKbLmQSDfJTng5dMY) - OLD?
[PRD: User List with Current Course  Annotation Count Generation](https://docs.google.com/document/d/16EhZf83rP2yU6PasLEsIoa6S_-cApTcHPYG24FNCOcE)  - OLD?
[PRD: Automatic Email Campaigns](https://docs.google.com/document/d/1NFaWV6k_7EgTxHU0iXDDOXihwEZY9H-_H6sHTj0vjZk/edit) - Draft?
## Tasks

Dash related:

_This isn't technically part of the project, but hey, too late now_

 * [x] Create a user dashboard
     * [x] Basic details about the user
     * [x] This should have the last login 
 * [x] Add `h_user_id` field to Hubspot prod
 * [x] Add a calculated field in Hubspot that is a link back to the dashboard
 * [x] Sync it all to the QA sandbox
 * [x] https://github.com/hypothesis/report/pull/236

Email campaign related:

 * [x] https://github.com/hypothesis/lms/pull/5502
    * [x] Run it, but only when Report is expecting the fields!
 * [x] Add required fields to Hubspot prod
     * [x] `lms_last_active`
     * [x] `lms_annotations_this_semester`
     * [x] `reporting_last_update`
 * [x] Sync it all to the QA sandbox
 * [x] https://github.com/hypothesis/report/pull/234
    * [x] https://github.com/hypothesis/report/pull/237
 * [x] Use these values instead of the hand rolled reports in the user dashboard

### Last first login `lms_last_login`

We don't really have anything good here as our data doesn't go back far, but we can use the user create date instead.

### Last active `lms_last_login`

I think we are using last login for that effectively. A person can be active by either logging in, or annotating. But you can't annotate without logging in, so effectively that's what it is.

### User id `h_user_id`

This isn't the LMS user id, this is the `h` user id. Each LMS user has one unique `h` user it is associated with, but each `h` user can have many LMS users. This is the:

* Region (e.g. `ca`)
* Then a dash `-`
* Then the H internal id as an integer

It's mostly not of use outside of reporting / digging around inside H.

### Annotations this semester (`lms_annotation_this_semester`)

Total annotations in linked courses, if you are a teacher in the most recent semester.

### Active courses this semester (`lms_active_courses_this_semester`)

Count of distinct courses with at least one annotation in the most recent semester.

**Comment by jon-betts** [comment]
The fields are in Hubspot. So this _might_ be done from a dev point of view. I suspect we need a ticket, or tickets about what's next?
