### ISSUE TITLE
Upgrade SQLAlchemy 1.4 -> 2.0

### ISSUE THREAD

**Issue by leedenison** [hypothesis/product-backlog#1461]
Tasks:
- [x] [Upgrade h to SQLAlchemy 2](https://github.com/hypothesis/h/issues/7973)
- [x] [Upgrade LMS to SQLAlchemy 2](https://github.com/hypothesis/lms/issues/5421)
- [x] [Upgrade Checkmate to SQLAlchemy 2](https://github.com/hypothesis/checkmate/issues/676)
- [x] [Upgrade report to SQLAlchemy 2](https://github.com/hypothesis/report/issues/215)
