### ISSUE TITLE
EPIC: Migrate client authentication from cookie-based to OAuth

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#159]
This is an epic tracking the various tasks needed to migrate the client from cookie to OAuth-based authentication.

Initially we are doing this to allow publishers to automatically log the user in to an account they created on their website as part of the publisher groups project. In future we want to extend this to first-party (ie. "native Hypothesis account") integration as well in order to enable:

* Third parties to create Hypothesis clients which use the REST and real time APIs
* Us to host the Hypothesis client on a different domain than the service and thus truly achieve separation between the client and service
* Avoid browser security restrictions on cookies in 3rd-party iframes (eg. User cannot log in to the Hypothesis client in Safari unless they have visited https://hypothes.is first in a top-level tab, Privacy Badger prevents logging into the client)

----

- [x] Enable the clients to use opaque OAuth access tokens for authentication
- [x] Provide a browser-compatible method of authenticating to the WebSocket using an access token
- [x] Make the client use an access token to authenticate to the WebSocket
- [x] Remove support in the service for authenticating to the WebSocket using cookies (hypothesis/h#4353)
- [x] Provide an API alternative for getting the user's profile (/app endpoint) (hypothesis/h#4333)
- [x] Provide an API alternative for updating a user's preferences (initially, for dismissing the sidebar tutorial)
- [x] Provide an API alternative for leaving a group (#157)
- [x] Provide an OAuth-based method for logging into Hypothesis ([spike](https://github.com/hypothesis/product-backlog/issues/292))
- [x] Provide a way to log-out of OAuth-based sessions ([Slack discussion](https://hypothes-is.slack.com/archives/backend/p1486117744003246))
