### ISSUE TITLE
Remove `serviceUrl` from client and service

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#215]
In order to get <https://github.com/hypothesis/product-backlog/issues/210> done we first need to remove the `serviceUrl` setting from the client and the service, replacing with with a "links" API endpoint that the service uses to communicate URL templates to the client (instead of the client generating them itself based on `serviceUrl`).

## Tasks

- [ ] <del>Move the group leave endpoint `POST /groups/:id/leave` into the API. It should move to something like `POST /groups/:id/leave` (exact details to be decided). We will have to continue to support the old URL as well until old versions of the client are no longer in use.</del> I moved this to a separate issue as it's backend, and can be done later: https://github.com/hypothesis/product-backlog/issues/229
- [ ] <del>Add the new group leave endpoint to [the API descriptor endpoint](https://hypothes.is/api/)</del>  I moved this to a separate issue as it's backend, and can be done later: https://github.com/hypothesis/product-backlog/issues/229
- [ ] <del>Make the client read the group leave URL from the API descriptor endpoint, instead of generating it itself</del> Made a separate issue for this: https://github.com/hypothesis/product-backlog/issues/230
- [x] Implement links descriptor URL in the web service, as described below
- [x] Change the client to get all its links from the links descriptor URL, instead of generating them based on `serviceUrl`
- [ ] <del>Remove the `serviceUrl` setting from the client and service entirely</del> Created a separate issue to do this later: https://github.com/hypothesis/product-backlog/issues/274

(I think you _could_ do the later tasks before doing the earlier tasks about moving the group leave endpoint into the API - the client could just read the group leave URL from the links endpoint like it reads other URLs, but know that the group leave one is a `POST` not a `GET`. Then once group leave has been moved into the API server-side this implicitly hard-coded knowledge can be removed from the client.)

## Reasons

This issue is the result of a series of Slack discussions:

* <https://hypothes-is.slack.com/archives/frontend/p1489432309156413>
* <https://hypothes-is.slack.com/archives/frontend/p1489488378820392>
* <https://hypothes-is.slack.com/archives/frontend/p1489501463223892>

The issue is that [the `/app.html` page](https://hypothes.is/app.html) of the hypothes.is website currently configures the client with an `apiUrl`, `serviceUrl` and `webSocketUrl`:

```html
<script class="js-hypothesis-config" type="application/json">
  {
    ...,
    "serviceUrl": "https://hypothes.is/",
    "websocketUrl": "wss://hypothes.is/ws",
    "apiUrl": "https://hypothes.is/api/",
    ...,
  }
</script>
```

These URLs are currently _not_ part of [the `services` configuration setting](http://h.readthedocs.io/projects/client/en/latest/publishers/config/#cmdoption-arg-services) but they surely ought to be part of what defines "an annotation service" so they _should_ be part of the `services` setting.

The `services` config setting can be set by websites that [embed the Hypothesis client](http://h.readthedocs.io/projects/client/en/latest/publishers/embedding/), whereas the URLs above currently cannot be. Once they've been moved into `services` they will be able to be set by host websites. So it will be possible for a host website to configure its embedded client to use a non-hypothes.is annotation service, which is not possible currently.

But if a website embeds the Hypothesis client and customises what annotation service(s) it connects to, we don't want the website to have to specify all three URLs:

```html
<script class="js-hypothesis-config" type="application/json">
  {
    "services": [{
      "serviceUrl": "https://hypothes.is/",
      "websocketUrl": "wss://hypothes.is/ws",
      "apiUrl": "https://hypothes.is/api/",
      ...
    }]
  }
</script>
```

It would be nicer if the website only had to specify the one URL:

```html
<script class="js-hypothesis-config" type="application/json">
  {
    "services": [{
      "apiUrl": "https://hypothes.is/api/",
      ...
    }]
  }
</script>
```

And then the client would be able to discover by talking to the API, starting from just `apiUrl`, what the `serviceUrl` and `websocketUrl` are.

**But actually the `serviceUrl` should be removed entirely**, and that's what this issue is about. Note that this issue is _not_ for moving `apiUrl` into `services` (that's <https://github.com/hypothesis/product-backlog/issues/210>), this one is about getting rid of `serviceUrl`, which is necessary in order to be able to move `apiUrl` into services as described above.

All the client uses `serviceUrl` for is to generate URLs to HTML pages of the annotation service. [This file is believed to define all of the URLs the client generates from `serviceUrl`](https://github.com/hypothesis/client/blob/master/src/sidebar/service-url.js#L11). But the client shouldn't be generating these URLs - it should be getting them from the API.

So the client should be able to start from just the `apiUrl` from the `services` config, talk to the API, and discover all the other links it needs - all those links that the client was previously generating from the `serviceUrl` setting, plus the `websocketUrl`. `serviceUrl` as such can then go away.

The proposal for how to do this is to add a "links" page, maybe at `hypothes.is/api/links`,that would return all the links:

```
GET /api/links

{
  account_settings: "https://hypothes.is/account/settings",
  forgot_password: "...",
  groups_new: "...",
  help: "...",
  signup: "...",
  search_tag: "https://hypothes.is/search?q=tag:\":tag\"",
  user: "https://hypothes.is/u/:user"
}
```

This would have the side benefit of decoupling the client from the service a bit more. For example if we changed a URL in the service, we would not need to change that in the client as well (and do a client release, and maybe continue to support the old URL until old clients go away...)

Note that this will _not_ simplify the client code. In fact it probably adds complexity - currently the above URL templates are hardcoded into the client, but after the changes requested in this issue the client will have to make an additional HTTP request to get them, and in both cases the client still needs to be able to expand the URL templates. But in future we'd hope to move at least some of the above URLs out of the dumping-ground links endpoint and into more specific endpoints. For example whenever an API returns information about a user, that data will include the already-expanded profile URL for that user. There will no longer be any URL templates that the client sees, it just gets pre-expanded URLs from the service. _Then_ the client will hopefully be simpler than it is now, as it won't need to know anything about expanding URL templates.
 
Details:

* These are all `GET` links, if a URL is an API or requires non-`GET` requests it should be described in the <https://hypothes.is/api/> descriptor and not in the above links page

* The one link that the client currently generates from `serviceUrl` that is not a `GET` is the `POST /groups/:id/leave` for leaving a group. That should move under `/api/` and should go into the `/api/` descriptor and not into the links descriptor.

* The format for the URL templates above is the same one that <https://hypothes.is/api/> uses. It's the format for Angular's services. We're proposing just to reuse this format for now, although changing everything to [RFC6570](https://tools.ietf.org/html/rfc6570) UI templates one day might be a good idea.

Questions:

* What about `websocketUrl`? Does it just go in the above links endpoint alongside the other links?

* What should be the URL of the links descriptor? Above I've used `/api/links`

* How does the client discover the links URL? It seems like either the client needs to know how to generate the links URL based on the `apiUrl`, or the API descriptor endpoint (`https://hypothes.is/api/`, a.k.a. `apiUrl`) needs to contains the links URL.
