### ISSUE TITLE
TASK: Configure https://web.hypothes.is

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#247]
### Context

EPIC: this card doesn't have an epic but [this document](https://docs.google.com/document/d/1tselsMg9nB8r0tv93t6wx8j93tQjgDOGdoe4_nhFWRM) provides an overview of the project this is a part of and the motivations for it.

We are planning to move those parts of the https://hypothes.is domain currently served by WordPress (broadly, the marketing/PR content, documentation, and the blog) to a separate domain, https://web.hypothes.is

### Task

Configure the https://web.hypothes.is domain so that it serves the new website, and configure any associated dev and test domains.

### Subtasks

- [x] Ensure new website is configured appropriately in [Pantheon](https://pantheon.io/) (If you need access, ask @xolotl)
- [x] Configure `dev-web.hypothes.is` origin cert in Cloudflare and Pantheon
- [x] Configure `dev-web.hypothes.is` domain in Cloudflare
- [x] Configure `qa-web.hypothes.is` origin cert in Cloudflare and Pantheon
- [x] Configure `qa-web.hypothes.is` domain in Cloudflare
- [x] Configure `web.hypothes.is` origin cert in Cloudflare and Pantheon
- [x] Configure `web.hypothes.is` domain in Cloudflare
- [x] Check that appropriate CSP/X-Frame-Options headers are configured for Pantheon. **BLOCKED** on the new WordPress theme (custom headers go in the theme's `functions.php`).

### Issues to resolve

- [x] ~~Does the new site need password protecting before launch?~~ Up to @xolotl and co. Easily toggled on and off from Pantheon dashboard.
- [x] ~~Do we have a QA environment for WordPress?~~ Pantheon supplies `dev`, `test`, and `live` environments.
