### ISSUE TITLE
TASK: Make h service serve redirects for migrated website content

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#248]
### Context

EPIC: this card doesn't have an epic but [this document](https://docs.google.com/document/d/1tselsMg9nB8r0tv93t6wx8j93tQjgDOGdoe4_nhFWRM) provides an overview of the project this is a part of and the motivations for it.

As part of the migration of non-application content to the https://web.hypothes.is domain (see #247), we will need to serve redirects from the old content locations to the new content locations on https://web.hypothes.is.

### Task

Serve appropriate redirects for this content from the `h` service. 

*N.B.* These can be added before we make the new site live, so long as the current nginx configuration in `h` prevents them from being seen in production (which will be the case if the redirects are served by the Python application).

### Subtasks

- [x] Obtain lists of exact redirects and prefix-redirected content from the website team (@nateangell)
- [x] Serve redirects for this content from the h service

### Issues to resolve

- [x] ~~Are these all 301 redirects? Is there any content which will not be redirected?~~ Yes and no, respectively.
- [x] ~~Will a list of hard-coded exact and prefix redirects from the application be ok?~~ Yes.

### Points

2017-04-05: 5
