### ISSUE TITLE
TASK: Make h service homepage redirect to appropriate content

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#249]
### Context

EPIC: this card doesn't have an epic but [this document](https://docs.google.com/document/d/1tselsMg9nB8r0tv93t6wx8j93tQjgDOGdoe4_nhFWRM) provides an overview of the project this is a part of and the motivations for it.

When the marketing/PR/docs/blog content moves to https://web.hypothes.is (see #247), the root URL of the web application should redirect the user to an appropriate location based on their logged-in status.

### Task

When a user visits https://hypothes.is, they should be:

- redirected to `https://web.hypothes.is/` if they are logged out
- redirected to `https://hypothes.is/users/<me>` if they are logged in (i.e. their user's activity page)

**N.B.** This behaviour should be feature flagged.

### Subtasks

- [ ] Serve a 302 redirect to https://web.hypothes.is when a user is logged-out.
- [ ] Allow this URL to be overridden from config so that (for example) https://qa.hypothes.is can redirect to https://qa-web.hypothes.is instead.
- [ ] Serve a 302 redirect to the user's activity page if they are logged-in.
