### ISSUE TITLE
TASK: Complete the removal of memex package

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#255]
### Context

For full context, see [this longer note](https://notes.wtk.io/2017/03/08/reintegrating-memex). The following is a condensed version of that document.

`memex` was made a separate package with a view to releasing it independently of the rest of the h application for reuse by others. Many of the assumptions that motivated that decision have either been invalidated or are no longer relevant.

We can substantially reduce the cognitive overhead needed to understand the `h` codebase by integrating memex models into `h.models`, memex views into `h.views`, and so on.

### Task

Complete the reintegration of the `memex` package with the rest of the `h` software.

### Subtasks

The aim here is to move the items with the fewest dependent modules first, so as to minimise the number of imports to modules in `h` from modules in `memex`.

- [x] Move routes
- [x] Move views
- [x] Move `memex.cors`
- [x] Move `memex.storage`
- [x] Move presenters
- [x] Move `memex.search`
- [x] Move `memex.eventqueue`
- [x] Move `memex.events`
- [x] Move groupfinder service definition
- [x] Move `memex.schemas`
- [x] Move `memex.resources`
- [x] Move `memex.links`
- [x] Move models
- [x] Move `memex.uri`
- [x] Move query utilities
- [x] Move `memex.parse_document_claims`
- [x] Move `memex.markdown`
- [x] Move `memex.db`
- [x] Clean up package (remove `setup.py`, simplify `tox.ini`, `.travis.yml`, etc.)
- [x] Update docs
- [ ] Remove all references to the `memex` name from the codebase
