### ISSUE TITLE
TASK: Shut down old WordPress service after migration to Pantheon

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#275]
### Context

The `wpdb` server runs MySQL and Redis for our WordPress service, which itself runs in Skyliner.

After we have migrated the PR/marketing website to https://web.hypothes.is (which runs on Pantheon), these services can be shut down.

### Task

Shut down old WordPress service after migration to Pantheon.

### Subtasks

- [x] Shut down and remove WordPress application in Skyliner.
- [x] Shut down `wpdb` instance.
- [x] Remove `wpdb` instance.
- [x] Clean up any unused code in `playbook` associated with `wpdb` or `db` instance types.
