### ISSUE TITLE
SPIKE [1w]: OAuth/cookieless login

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#292]
## Context

We wish to make it possible to login from the sidebar [without cookies](https://github.com/hypothesis/product-backlog/issues/159).

## Questions that need answering

- [x] ~~What is the login/logout user journey from the sidebar going to look like?~~ (Partially resolved: See the [design doc](https://docs.google.com/document/d/149Fntx5fQlrnjW5bgqC0booVlWOBZV4g1oFkpArh-QI/edit#heading=h.916qr9zamvn2) for the default login/logout flow for "a browser-based OAuth client". There is still an outstanding question about how exactly we'll optimize this for trusted clients).
- [x] ~~How is credential storage in the extension going to work?~~ https://github.com/hypothesis/product-backlog/issues/315
- [ ] ~~How are we going to feature-flag this (since it affects logged-out users)~~ (Discussion in https://github.com/hypothesis/product-backlog/issues/313)
- [ ] ~~Is it possible to have a cookie-based fallback for the bookmarklet, via or other related use-cases?~~ (#321)
- [ ] ~~What is migration of the client going to look like?~~ (#320)
- [ ] ~~What is the first user experience going to be like for a new user after this? How do we optimize it?~~ (#322)

## Outputs

- [Design doc](https://docs.google.com/document/d/149Fntx5fQlrnjW5bgqC0booVlWOBZV4g1oFkpArh-QI/edit#heading=h.916qr9zamvn2)
- List [of issues](https://github.com/hypothesis/product-backlog/labels/OAuth) for implementation

**Comment by robertknight** [comment]
I have updated the description with the outcome so far. Where we have got to is:

- The user flow and technical design for browser-based OAuth clients is described in the [design doc](https://docs.google.com/document/d/149Fntx5fQlrnjW5bgqC0booVlWOBZV4g1oFkpArh-QI/edit#) along with the changes we'll need in the service.
- There is a working prototype in the "oauth-login-prototype" branches in the service and client
- A bunch of issues have been filed and [labeled OAuth](https://github.com/hypothesis/product-backlog/labels/OAuth).
- We have some major unresolved questions:
  - (1) How are we going to put this behind a feature flag for testing, bearing in mind this flag is needed before & after login.
  - (2) To what extend do we try to keep the login in sync between the web service, the embed and the extensions? In particular, this is relevant when using the service and the client for the first time.

There are several ways we could do (1), we just need to pick something reasonable. (2) does need to be resolved. The default answer for an OAuth client would be that the client login is separate from the service, and therefore:
- The first time the user uses the embedded client OR extension, having created an account on the service (and being logged in there), they will need to click "Login" in the client and then "Authorize" in a popup (we might change the wording and label for trusted clients)
- If the user logs out of a client (embed or extension), that will only log them out of _that_ client and not other clients or the web service.
- Usage of the client does not extend the user's session lifetime on the service as it does today. That means that if you only use the client for a few days, you might find yourself logged out of the service the next time you go to visit it.

Some possible solutions:
- Use OAuth for first-party clients, but:
  - Optimize the first-usage experience for both the embed and the extensions. If the client loads and is not logged in, make the client attempt to call to a cookie-authenticated "auto-authorize" endpoint which returns an auth code (or perhaps access/refresh token directly) _if_ the user is logged in to the service. If this doesn't work (because the user is not logged in, or their browser blocks cookies in this context, or this is a fork of the client served from a different domain) then the user will just have to go through the default OAuth flow.
  - Flag "trusted" clients in the DB and streamline the auth flow for them by removing the "Authorize" step after logging in via the popup. If the user visits the popup when they are already logged in, they will see "softer" text, eg. "Continue as <username>" rather than "Accept / Deny".

**Comment by ajpeddakotla** [comment]
@fatbusinessman is going to break this card up into smaller problem cards and close this out .

**Comment by dhwthompson** [comment]
@fatbusinessman has now broken this card up into smaller problem cards. A few of them could still use a clearer articulation of the problems they’re trying to solve, but that’s something that we can flesh out over time.

Closing this spike as “done enough for now”.
