### ISSUE TITLE
SPIKE [3d]: Evaluate Elastic Beanstalk for Skyliner replacement.

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#297]
## Context

We need to know if Elastic Beanstalk is a workable [replacement for Skyliner](https://github.com/hypothesis/product-backlog/issues/295) and what steps will be needed to migrate if so.

## Questions to answer

- [x] ~~What modifications, if any, will be needed to get our existing Dockerized applications to run in the EB environment?~~ At the moment, we aren't aware of any substantive changes that will be needed.
- [x] ~~What automation code will be needed to create the VPC/networking/other resources currently managed for us by Skyliner for an EB-based solution?~~ No new code necessary, but we will need to provision new security groups for instances and new load-balancer-specific subnets within our existing `hop-prod` VPC.
- [x] ~~What kind of replacement for the Skyliner deployment dashboard can we reasonably cook up?~~ We can fairly easily have Jenkins jobs with "push-button" deployment. We aren't exactly sure yet how easily we can do "redeploy QA/prod" or "deploy to prod" buttons that don't require any further user input, but we _think_ this should be possible. We're also likely to lose the visual diff of code and config changes that are about to be deployed, but we may be able to replicate this in an uglier way in the short term. Long-term we could consider using something like Etsy's [deployinator](https://github.com/etsy/deployinator) to improve the situation here.
- [x] ~~How will we automate deployments to QA?~~ We can trigger the Jenkins deployment job after a successful build of `h`/`bouncer`/etc.
- [x] ~~How will "promotion" from QA to Prod work?~~ We do not know _exactly_ how this will work, but we envision storing the name of the last successful build deployed to QA somewhere (in Jenkins metadata or otherwise) and then using that for "prod" deployments.
- [x] ~~Roughly what will running our existing applications in EB infrastructure cost, per month?~~ The same or less than current infra in Skyliner, as the paid resources are pretty much identical.

## Output

- [x] ~~A summary evaluation which addresses the questions above, including a decision on whether to proceed with EB.~~ [See below](https://github.com/hypothesis/product-backlog/issues/297#issuecomment-305225775).
- [x] If we are going to proceed with EB, cards outlining the work necessary to migrate our infrastructure.

## Next steps

**N.B.** Crossed out **DOES NOT MEAN THE WORK IS DONE**. It means that the work has been split out into a separate card.

- [x] ~~Provision an instance security group (so everything can talk to `mon`) and an `app-h` security group (that allows `h` instances to talk to RDS).~~ https://github.com/hypothesis/product-backlog/issues/300
- [x] ~~Provision dedicated subnets for load balancers (one per AZ).~~ https://github.com/hypothesis/product-backlog/issues/301
- [x] ~~Finish end-to-end "spike" for `bouncer` so that we have at least: automated deployments to QA and manual promotion to prod.~~ https://github.com/hypothesis/product-backlog/issues/302
- [x] ~~Jenkins notifications to Slack (specifically for deployment, but perhaps more generally for all builds)~~ https://github.com/hypothesis/product-backlog/issues/303
- [x] ~~Update tools (e.g. `h-ssh`) and documentation for running tasks and/or database migrations for applications.~~ #304, #305
- [x] Update playbook docs on operability: accessing logs, scaling up and down, health monitoring, etc.
- [x] Plan and write-up a migration plan for the remainder of our applications.
- [x] Execute on the migration plan.

**Comment by nickstenning** [comment]
### Summary of spike investigations

Overall, it looks like **Elastic Beanstalk provides us a lot of what we need to replace Skyliner with no major blocking problems**. Coupled with the fact that it's an established product with very little chance of disappearing in the near term, it seems like our best option.

In particular, most of the other potentially attractive options would require us to migrate our existing data stores to a new AWS region. While this is something we probably do want to do eventually (`us-west-1` is expensive, old, and undermaintained compared to `us-west-2`), we don't want to have to do it at the same time as another major infrastructure migration.

We have a [mostly-automated](https://github.com/hypothesis/deployment) deployment of bouncer in QA up and running after a day or two's work.

I've run through the plan with the team in our Eng Biweekly meeting today, and fielded some questions.

Additional work is summarised on the above card under "Next Steps," and we'll split these out into cards.
