### ISSUE TITLE
TASK: Set up Elastic Beanstalk deployment for bouncer

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#302]
## Context

In order to prove to ourselves that we can replicate (enough of) Skyliner with Elastic Beanstalk, we want to get an end-to-end deployment of `bouncer` running.

## Task

Get deployment of `bouncer` working in a way that's reasonably close to what we want to do for all our applications.

## Subtasks

- [x] ~~Set up Jenkins job which can manually deploy bouncer~~
- [x] Give each bouncer build a specific version number (hypothesis/bouncer#44)
- [x] Set up automatic deployments to QA (hypothesis/bouncer#45)
- [x] Set up (ideally) "one-click" promotion to production (at least: don't require developers to provide a version number, hypothesis/deployment#3).
- [x] Check resource allocation (i.e. instance size/count, etc. - [see comment below](https://github.com/hypothesis/product-backlog/issues/302#issuecomment-306450303))
- [x] Set-up grafana dashboard (https://mon.hypothes.is/grafana/dashboard/db/bouncer-eb)
- [x] Set up production environment with environment variables
- [x] Migrate bouncer DNS.

**Comment by chdorner** [comment]
I've configured `t2.nano` instance types for both the QA and the prod environment last week. We also run one instance per environment, so this is the same as with our Skyliner setup. With one difference, which is that Beanstalk by default configures autoscaling for up to 4 instances (per environment) when the network out metric reaches >6MB (6,000,000 bytes) for more than 5 minutes at a time. In the recent two weeks, the biggest spike we had for bouncer production was 718kB (718,938 bytes), so we would not have triggered any autoscaling event.

I don't think any of the auto-scaling will be an issue for bouncer, but it's good to have it in place. If network-out is the best metric remains to be seen (or researched), but that should happen with `h` or `via` which will receive much more spiky traffic.

**Comment by chdorner** [comment]
This is all done except for actually switching over the production DNS entry. Considering it is Friday, this should be done early next week.

**Comment by chdorner** [comment]
Switched the production DNS at 2017-06-13 10:04 UTC.
