### ISSUE TITLE
STORY: Database migrations for Elastic Beanstalk

### ISSUE THREAD

**Issue by dhwthompson** [hypothesis/product-backlog#305]
# Context

Skyliner currently offers us a way to run database migrations from the dashboard. Without Skyliner, we’re going to have to have some other way of running these.

# Task

The minimum version of this is to tell developers to SSH into the servers and run migrations through the `hypothesis migrate` command-line tool. This is the easiest to set up, but it’s more error-prone and harder to track. Another option might be to set up a job in Jenkins.

# Acceptance criteria

* [x] There is a standard way to run migrations against the `h` database
* [x] There is documentation about how it works

# More details

We currently have tasks to:

* Migrate one revision up
* Migrate to the latest revision
* Roll back by one revision
* Display the current revision

**Comment by chdorner** [comment]
I did some research this morning. The possible solutions for this:

## 1. Manually SSH'ing into the instance

Job done, nothing to do (except for documentation).

Pros:
* No work to implement
* We can run any kind of command either on the instance or in the docker container

Cons:
* Cumbersome for people to do
* Everybody needs to have access to the `ops.pem` key (they already have)
* No audit trail of who ran what and when

## 2. Automatically migrate after deploy

We can configure commands (instance or container commands) that run after an instance gets added to the Elastic Beanstalk environment. It is also possible to configure these commands to either run on all instances or only on one (leader).

Pros:
* Easy to implement
* Always up-to-date with database migrations
* Implied audit trail, person who deployed is the person who migrated the DB

Cons:
* As long as we use the same database for QA and prod this can be quite dangerous because a QA deployment will **automatically** upgrade the production database.

## 3. Jenkins job that SSH'es into one instance and runs a command

We can create a Jenkins job for the various commands that we need to run regularly (see list above, plus re-index search index, etc.).
Since we use autoscaling instances can get terminated at any given point in time. We can work around this by protecting the instance before running the command (`aws autoscaling set-instance-protection`), and lock the Jenkins job so a deploy cannot happen at the same time.

Pros:
* Easy to use for developers
* Audit trail (person kicking off the Jenkins job)

Cons:
* Need to figure out a way for the Jenkins server to securely SSH into Elastic Beanstalk instances (basically the Jenkins instance needs the `ops.pem`)

## 4. SSM agent on instances + EC2 Run Command

This is very similar to how [Skyliner Tasks](https://www.skyliner.io/help/tasks) are implemented.

We can configure an [instance command](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-commands) which [installs and runs the AWS SSM agent](http://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html). The instances are then registered with the EC2 Systems Manager and we can run commands through the [Run-Command interface](http://docs.aws.amazon.com/systems-manager/latest/userguide/walkthrough-cli.html). 

Pros:
* Easy to use for developers
* Audit trail
* No SSH'ing into Elastic Beanstalk instances

Cons:
* More work at setting up (maybe not much more than the Jenkins SSH solution)

---

I will go with the last option, which is the cleanest and does not involve SSH'ing from Jenkins to the Elastic Beanstalk instances.

**Comment by chdorner** [comment]
TODO list:

* [x] Install SSM agent on instances (:arrow_right: hypothesis/deployment#11)
* [x] Add `AmazonEC2RoleforSSM` policy to `aws-elasticbeanstalk-ec2-role` role in Ansible playbooks (:arrow_right: hypothesis/playbook#142)
* [x] Create S3 bucket through ansible for command output logs (:arrow_right: hypothesis/playbook#142)
* [x] Write script that 1. selects an instance, 2. protects the instance from scale-in, 3. runs a command through ssm, 4. tails the output of the command, 5. removes scale-in protection (:arrow_right: hypothesis/deployment#11)
* [x] Jenkins configuration (:arrow_right: hypothesis/deployment#12 and https://jenkins.hypothes.is/job/h-tasks)
* [x] Documentation: (:arrow_right: hypothesis/playbook#146)
