### ISSUE TITLE
TASK: Set up Elastic Beanstalk deployment for via

### ISSUE THREAD

**Issue by chdorner** [hypothesis/product-backlog#309]
## Context

In order to prove to ourselves that we can replicate (enough of) Skyliner with Elastic Beanstalk, we want to get an end-to-end deployment of `via` running.

## Task

Get deployment of `via` working in a way that's reasonably close to what we want to do for all our applications.

## Subtasks

- [x] Set up Jenkins job which can manually deploy via
- [x] Give each via build a specific version number ([see here](https://github.com/hypothesis/via/compare/7e424f81cb54d4395ddf0a37cf0f5318b01c5110...a2cccd09a50ac98e9adbdbdf6af2e7430ab8c0d0))
- [x] Set up automatic deployments to QA
- [x] Set up (ideally) "one-click" promotion to production (at least: don't require developers to provide a version number).
- [x] Check resource allocation (i.e. instance size/count, etc.)
- [x] Set-up grafana dashboard
- [x] Set up production environment with environment variables
- [x] Migrate via DNS.

**Comment by chdorner** [comment]
Similar to the bouncer ticket (hypothesis/product-backlog#302), everything here is done except for switching the DNS entry.
