### ISSUE TITLE
Support generating OAuth authorization codes and exchanging them for access/refresh tokens

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#311]
In order to implement the OAuth auth flow for the client as described in the [design doc](https://docs.google.com/document/d/149Fntx5fQlrnjW5bgqC0booVlWOBZV4g1oFkpArh-QI/edit#) the service needs to support generating authorization codes which can be exchanged for access and refresh tokens.

**Acceptance criteria**

1. The service has internal logic to generate short-lived, single-use authorization codes.
2. These authorization codes can be exchanged for an access and refresh token pair.
3. If the client has a client secret registered, this secret is verified when the auth code is exchanged.

**Comment by chdorner** [comment]
Todo:

* [x] Support authorization code exchange in token endpoint
* [x] Support `web_message` authorization code delivery mechanism
* [x] Fix 500 error when using `/oauth/authorize?client_id=...&response_type=token` (just fail with error message, fix: hypothesis/h#4612.
* [x] Fix 500 error when `authclient.response_type` is `None` and `OAuthValidator.validate_response_type` explodes (hypothesis/h#4613)
* [x] Fix 500 error when `request.client_secret` is None in `if not hmac.compare_digest(client.secret, request.client_secret):` (hypothesis/h#4614)
* [x] Revocation endpoint
