### ISSUE TITLE
TASK: Set up Elastic Beanstalk deployment for h

### ISSUE THREAD

**Issue by chdorner** [hypothesis/product-backlog#318]
## Context

This will get `h` up an running on our new Elastic Beanstalk-based infrastructure.

Note that currently with Skyliner, `h` is comprised of [hypothesis/h](https://github.com/hypothesis/h) and [hypothesis/h-periodic](https://github.com/hypothesis/h-periodic). We will most likely continue like this for now and then we can look for a nicer way to run celerybeat with EB.

## Task

Get deployment of `h` working in a way that's reasonably close to what we want to do for all our applications.

## Subtasks

- [x] Set up h-periodic to build Docker images on Jenkins (hypothesis/h-periodic#3)
- [x] Set up Jenkins job which can manually deploy h
- [x] Set up Jenkins job which can manually deploy h-periodic (hypothesis/deployment#6)
- [x] Set up automatic deployments to QA for h
- [x] Set up automatic deployments to QA for h-periodic
- [x] Check resource allocation (i.e. instance size/count)
- [x] Set-up grafana dashboard
- [x] Set up production environment with environment variables
- [x] Migrate h DNS.
