### ISSUE TITLE
Stop OAuth login loss by increasing refresh token TTLs

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#329]
## Problem that we're trying to solve with this card

Currently when the client is logged in via OAuth (for example when the client is embedded on a publisher site, such as the [publisher accont test site](https://github.com/hypothesis/publisher-account-test-site), and is using third-party accounts) it's easy for the client to miss its chance to refresh its access token, and end up with an invalid access and refresh token:

1. Log in to the client

2. Use the client for 54 minutes

3. Put your laptop to sleep for 10 mins

4. Wake your laptop 

   => The client's access and refresh token pair, which expire after one hour, have now expired. Because the tokens expired while the laptop was asleep, the client missed its chance to use the refresh token in a refresh request a few minutes before expirty and get a fresh access and refresh token pair.

   This can also happen if your operating system suspends your browser window because you're not using it, or your browser suspends your tab, or you temporarily lose your internet connection, etc.

When this happens the user sees a broken sidebar and must reload the page:

![peek 2017-04-27 13-33](https://cloud.githubusercontent.com/assets/22498/25483524/2347f9ac-2b4e-11e7-80c1-de0a3384581a.gif)

In the future, when we're also using OAuth for first-party users (e.g. a `seanh@hypothes.is` user logged-in to their Chrome extension) then instead of reloading the page the user will have to go through a popup window-based login process.

If the **refresh token** were still valid after the laptop was woken up again (even though the **access token** had still expired) then the client's refresh attempt after waking the laptop would have succeeded and all would have been well.

## Proposed solution to the problem

* **Increase the lifetime of our OAuth refresh tokens** so that the client never, or very rarely, ends up with an expired refresh token and has to ask the user to reload the page or login again.

* Specifically we propose to **increase the liftetime of refresh tokens to 7 days** so that it's the same as the lifetime of <https://hypothes.is/> website session cookies.

* This increased refresh token lifetime should apply **both to third-party accounts** (e.g. a `fred@elifesciences.org` Hypothesis account, which already use OAuth to login) **and to first-party accounts** (`seanh@hypothes.is`, the client currently does not use OAuth to login to these accounts but we're working on making it use OAuth for them).

The **hypothesis** is that if we do this then the expired refresh token issue will never occur or will occur infrequently enough that we don't consider it a problem. (We need metrics in place to measure this, see [Add metrics for OAuth token usage (product-backlog#170)][].

## Tasks

Things that we'll need to do in order to implement this proposed solution:

- [x] Add separate refresh token expiry times to the server-side model.

   The `token` table in the database (`h/models/token.py::Token` class in the code) is a single database table and model class that holds an access and refresh token pair. It currently has just a single `expires` field that holds a single expiry time that applies to both the access token and the refresh token.

   Add a new, nullable `refresh_token_expires` column to this database table (and corresponding field to the model class) that is just the same as the existing `expires` column:

   - [x] **Add `refresh_token_expires` model field and database column** (hypothesis/h#4622)

   - [x] **Add a boolean `refresh_token_expired` `@property`** to the `h/models/token.py::Token` class, the same as the existing `expired` property  (hypothesis/h#4623)

   - [x] **Create new refresh tokens with 7-day expiry times**. (hypothesis/h#4623)

      Change the code that creates OAuth access/refresh tokens (`h/services/oauth.py::OAuthService.create_token()`) to create tokens with a `refresh_token_expires` time (in 7 days) as well as the existing `expires` time (1 hour) that it already creates.

   - [x] ~**Write database migration script for existing tokens**.~

      We decided not to do this as we don't have any production use-case for OAuth yet, so we can just let the few test tokens that might be valid expire normally.

      All existing tokens **that have an `expires` value** should have their `refresh_token_expires` value set to `expires` + 7 days - 1 hour. Existing tokens with a `NULL` `expires` value don't need to be  changed (`refresh_token_expires` can remain `NULL`).

   New OAuth access/refresh tokens should now be created with a separate refresh token expiry time of 7 days, and preexisting tokens in the database should have had their refresh token expiry times filled in.

   The new refresh token expiry times are not used for anything, yet.

- [x] **Respect refresh token expiry times** in refresh requests. (hypothesis/h#4623)

   `h/services/oauth.py::OAuthService._verify_refresh_token()` currently looks at the token's `.expired` property (whether or not the **access token** has expired) to decide whether to allow a refresh request.  It should look at the new `.refresh_token_expired` property instead.

   After this task is done it should now be possible for a client to refresh an access token that has already expired, as long as its associated refresh token (that the client sends in the refresh request) has not yet expired.

- [x] **Truncate refresh token expiry times** after successful refresh requests. (hypothesis/h#4623)

   When a client successfully uses a refresh token to get a new access and refresh token pair, the expires time of the refresh token should be set to 3 minutes (unless it is already less than 3 minutes).

   The purpose of this is to reduce the negative impact of any refresh tokens somehow leaking out into the wild, whenever a refresh token is used we take the opportunity to reduce its lifetime so that if it does leak in future it will probably already expired and so won't be a threat.

   The reason we reduce the lifetime to a few mins, rather than expiring it immediately, is to allow legitimate clients to retry refresh requests if e.g. a network error means they don't receive the response.
 (Our client does not currently retry failed refresh requests, but it could and should do.)

   I think this will require changes to `h/services/oauth.py` and `h/views/api_auth.py`.

- [x] **Verify that everything works with our client**.

   I don't think any changes to our client should be necessary - it should just work.

   The relevant client code to look at is `src/sidebar/oauth-auth.js` and also see [Add OAuth refresh support (client#221)][], [Show an error message to the user when getting or refreshing an OAuth access token fails (client#385)][] and [Fix refreshing access tokens when laptop suspends (client#384)][].
      
   Currently, with both the access token and refresh token expiring after one hour, the client looks at the access token expiry time and tries to send a refresh request before it expires. With the new 7 day refresh token expiry times this refresh request should succeed just as it did previously.
   
   Currently, with both the access token and refresh token expiring after one hour, if the client misses its chance to use a refresh token (e.g. the access token expired while the laptop was asleep) then when it gets a chance (when the laptop wakes up) the client tries, pointlessly, to refresh the token anyway and gets an error from the server. With the new 7 day refresh token expiry times this previously pointless refresh request should now succeed.

- [x] ~**Add the refresh token expiry to the server's API response**.~

   We decided against doing this. There is no mention in the spec about returning the expiration time of a refresh token, and other implementations don't include this in the response at all.

   When the client makes a grant token or refresh token request and receives a new access token and refresh token pair from the server, this server response currently contains the expiry time of the access token only.

   Look up the correct way to render refresh token expirty times in authorization server responses according to the OAuth 2.0 spec, and add the refresh token expiry times to our server's responses.

   Our client will not (and does not need to) actually look at refresh token expiry times, it needs the access token expiry only and when the access token has expired (or is close to expiry) the client just blindly tries to use the refresh token and hopes that it works. But given that we do have separate refresh token expiry times it seems correct to include them in the server responses.

- [x] **Simplify client code to remove assumption that tokens have to be refreshed before access token expires**. The `oauth-auth` service in the client currently assumes that tokens have to be refreshed before the access token expires. It should be possible to simplify the service somewhat after this requirement is removed.

## Security implications of this change

* In Hypothesis a refresh token can be used on its own (without also requiring an access token, client secret or anything else) to get a fresh access and refresh token pair that can be used to access the Hypothesis API.

* This grants permanent access to the API as you can keep on using the next refresh token to get a fresh access and refresh token.

* This might have been one reason why the lifetimes of refresh tokens were originally set so low in Hypothesis.

* By greatly increasing the lifetimes of refresh tokens (from one hour to seven days) we increase the chances that, if a refresh token leaks, it will still be alive and usable when it gets into the hands of an attacker.

  For example if we discovered that the plain text of a lot of Hypothesis API requests and responses from different users clients had leaked, then any refresh tokens that were contained in the leak and that were issued within 7 days of when the leak happened would be potentially compromised.

* **However** the client will normally use a refresh token within an hour (because the access token still expires in an hour) and when the refresh token is used the server will truncate its lifetime. So in practice the vast majority or refresh tokens will only actually live for hours, not 7 days.

* So ... this change **does** make things a bit less secure, but **seanh doesn't think it's a big loss** of security.

## See also

* [Add metrics for OAuth token usage (product-backlog#170)][]
* Original github issue that this issue was based on: [Extend refresh token TTL for first party accounts (product-backlog#312)][]
* [Client OAuth Login Technical Design Google Doc][]
* Pull request that first added OAuth login support to the client: [Add OAuth refresh support (client#221)][]
* Pull request that added client error message when client's refresh token
  expires: [Show an error message to the user when getting or refreshing an OAuth access token fails (client#385)][]
* Pull request that fixed client refresh token handling with laptops suspending and waking up: [Fix refreshing access tokens when laptop suspends (client#384)][]

[Extend refresh token TTL for first party accounts (product-backlog#312)]: https://github.com/hypothesis/product-backlog/issues/312
[Client OAuth Login Technical Design Google Doc]: https://docs.google.com/document/d/149Fntx5fQlrnjW5bgqC0booVlWOBZV4g1oFkpArh-QI/edit#heading=h.916qr9zamvn2
[Add metrics for OAuth token usage (product-backlog#170)]: <https://github.com/hypothesis/product-backlog/issues/170>
[Add OAuth refresh support (client#221)]: https://github.com/hypothesis/client/pull/221
[Show an error message to the user when getting or refreshing an OAuth access token fails (client#385)]: https://github.com/hypothesis/client/pull/385
[Fix refreshing access tokens when laptop suspends (client#384)]: https://github.com/hypothesis/client/pull/384

**Comment by chdorner** [comment]
The backend part of this is done and deployed to production. I'll assign this to @robertknight so he can track the changes in the client.

**Comment by robertknight** [comment]
This is done and shipped.
