### ISSUE TITLE
pre-launch for Activity pages - Determine and Fix URL and bouncer links

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#37]
There are several issues that are tracking the changes that are needed to implement and fix URLs that are needed to direct users to various components on the user and group profile pages. 

Consider this a parent issue that will track the others. 

- [x] https://github.com/hypothesis/h/issues/4004 (New user and group URLs are confusing) **SeanH**
- [x] https://github.com/hypothesis/h/issues/4141 (Unnecessary `?q=` at end of URLs) **SeanH**
- [x] https://github.com/hypothesis/h/issues/4060 (Make tags links in document buckets) - https://github.com/hypothesis/h/pull/4091
- [x] ~~https://github.com/hypothesis/h/issues/4061 (Add direct links to annotation cards)~~ **Sheetal** (Tracked separately as https://github.com/hypothesis/product-backlog/projects/1#card-960193 )
- [x] https://github.com/hypothesis/h/issues/4059 (Make "Annotators" links in document buckets) - https://github.com/hypothesis/h/pull/4091
- [x] https://github.com/hypothesis/h/issues/4058 (Make URLs in document buckets links) - https://github.com/hypothesis/h/pull/4090 (**Done**) **Rob**
- [x] https://github.com/hypothesis/h/issues/4070 (Direct user to their profile page after login) - https://github.com/hypothesis/h/pull/4092
