### ISSUE TITLE
Publisher group icons

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#419]
As a publisher I want my **icon** to appear next to my groups (so that...?)

Done when:

- [ ] A Hypothesis developer can specify an icon image for a publisher when they
      create one. (How do we upload the image files? For example we may need a URL
      for each publisher icon. We may need to upload the icon somewhere somehow so
      that we have a URL for it.)
- [ ] The icon is shown next to the publisher's open groups in the groups menu
- [ ] The icon is shown next to the group in the top bar, when an open group is
      selected
- [ ] Icons are optional, not every publisher has to have one.
      (What will be shown in the groups menu and top bar when a publisher has no
      icon?)

Mockup:

![icons](https://user-images.githubusercontent.com/22498/35056817-d72ba6f8-fbaa-11e7-9eaf-79e5a4ebac54.png)

**TODO:** @dawariley Can you replace this mock up? Problems: The selected group is **Author's notes** but there is no Author's notes group in the menu!

**Comment by seanh** [comment]
Closing in favour of https://github.com/hypothesis/product-backlog/issues/502
