### ISSUE TITLE
Minimal Restricted Groups for Publishers

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#496]
### User Story: 
As a publisher I want to control the membership of a group that anyone can read, but that only members can write to, so that I can limit annotations to my staff, authors, invited experts, etc and not need to moderate the annotations.

### Acceptance Criteria: 
- [x] Group must be given a name
- [x] Groups are scoped to an origin or to multiple origins
- [x] A single origin can have more than one group
- [x] The group doesn't appear on any other sites other than those that the group has been scoped to. 
- [x] The group appears in the groups menu in the client whenever the client is launched on a URL that's within the group's scopes
- [x]  The group appears on no matter who is logged in (anyone can read the annotations) 
- [x] The group appears even when no one is logged in
- [x] Only group members can create annotations in the group 
- [x] The group looks just like any other group (for now) #489 addresses the markings that a restricted group might have in the near future
- [ ] Restricted groups have the private groups icon (for now): https://github.com/hypothesis/product-backlog/issues/513

- [x] Sort order of groups in the client's groups menu:

  1. All open groups and restricted groups are shown first, in alphabetical order (so different open and restricted groups will be interleaved with each other, if alphabetical ordering determines that)

  2. The _Public_ group is shown next, after the open and restricted groups

  3. All of the user's private groups are shown last, in alphabetical order

  Example, showing open and restricted groups mixed together in alphabetical order, then the Public group, then private groups in alphabetical order:

  * (w) Annotators Anonymous Open Group
  * (p) CNN Restricted Group
  * (w) Dinosaur Fans Open Group
  * (w) Public
  * (p) My Private Group One
  * (p) My Private Group Two

  Here `(w)` means the world icon, shown next to open groups and the public group, as it is currently. And `(p)` means the private group icon, shown next to private groups as it is currently and also next to the new restricted groups.

Issues to fix:

- [x] Right now, if you are the creator of a restricted group, you see the restricted group in the client's groups menu twice. https://github.com/hypothesis/product-backlog/issues/514

**Comment by lyzadanger** [comment]
Sorting question: Should open and restricted groups appear in group listings (e.g. client drop-downs) as one grouping (i.e. they'd be sorted alphabetically, interleaved) or separately (e.g. open, then restricted groups or vice versa)?

**Comment by dawachan** [comment]
Determination of sort order is bigger than just this issue but in answer to your question:
Some of the original thinking on the sort order of groups completed before the holidays:
(from conversations/requirement gathering with Dan and Heather)

- Groups are ordered by authority as designated by the publisher.
- Groups are organized under domains.
- Order of domains can be overridden by the publisher, default alphabetical.
- Nb. Sort order can be revised as we scale the number of groups.
 

The original groups control design (posted in eng-general yesterday) below assumes that groups are sorted alphabetically and group type (restricted vs open) is ignored. 

![screen shot 2018-02-23 at 10 58 05](https://user-images.githubusercontent.com/5212631/36603305-5666e014-1888-11e8-8db6-62ba102edd11.png)


Given the volume of groups users might have in their control it might be that a further filtering/sort mechanism is required to limit the amount of groups on display/sorting them - but the previous consensus was that given that we are only introducing a few groups from the get go we should start simple hence the earlier thinking "Sort order can be revised as we scale the number of groups."

**Note:** In the light of the larger groups control SOW and issues raised in the 'Grouping groups' issue: #418 and potentially exposing the 'Only Me' as a separate category based on the UX changes required in restricted groups #424 - I  need to take some time to think about the sort order holistically. I'm still at the QDR workshop and OOO Monday but will hop back on it Tuesday - happy to brainstorm with you @lyzadanger, I'd like to take some time to think through #418 and do some mocks as a 'straw man'.

**Comment by seanh** [comment]
I've broken out a separate card (and added it to the sprint) for doing the service-level part of creating restricted groups: <https://github.com/hypothesis/product-backlog/issues/499>. Assigned @sheetaluk to that card as she's working on it. Also assigned @sheetaluk to this card since she's working on a card that it a split-out part of this card! (But of course probably most or all of us should be assigned to this card.)

**Comment by ajpeddakotla** [comment]
A rewording of requirements regarding sort order: 

> Sorting question: Should open and restricted groups appear in group listings (e.g. client drop-downs) as one grouping (i.e. they'd be sorted alphabetically, interleaved) or separately (e.g. open, then restricted groups or vice versa)?

* The top group is the default (scoped) group. 
* If there is more than one scoped group on a domain, the groups are sorted alphabetically, agnostic of wether the groups are open or restricted groups `(i.e. they'd be sorted alphabetically, interleaved)`
* The publisher should be able to sort the groups in whichever way they desire and override the default settings determined by Hypothesis. 

NOTE: We will be changing these requirements as we scale our groups work in the future. This is our first pass at determining sort order. 

I actually think these requirements fit on #418 too @lyzadanger

**Comment by dawariley** [comment]
the same as I mentioned above @ajpeddakotla based on the earlier work i did in response to lyza's original question ;)

**Comment by dawachan** [comment]
note: these are the same requirements i posted earlier and which the visual directly represents which i understand were found to be 'confusing' during the restricted groups sync meeting. i'm happy to elaborate further @lyzadanger if it is still confusing and amend the visual accordingly. thanks!

@sheetaluk let me know when is a good time to walk through the comments i added above or if you have any questions about the visual i posted earlier. i'd like to get a better idea of how close we are aiming to get to the group control design I posted with this card and if i need to produce a new mockup to support this card, thanks!

**Comment by seanh** [comment]
I think we need to keep this as simple as possible for our first iteration on restricted groups, folks.

Lets try to keep this card as small as possible and as much as possible try to move separate features and design changes onto their own cards.

Lets focus this card on just getting a minimal restricted group - a group that anyone can read but that only members can write to - working, without any visual design changes to the client or adding any new features (grouping groups under publishers or domains, having a "default" group, allowing publishers to change the sort order of groups...).

For this card, let's just do this for the order of the groups in the menu:

1. All open groups and restricted groups are shown first, in alphabetical order (so different open and restricted groups will be interleaved with each other, if alphabetical ordering determines that)

2. The _Public_ group is shown next, after the open and restricted groups

3. All of the user's private groups are shown last, in alphabetical order

Example, showing open and restricted groups mixed together in alphabetical order, then the Public group, then private groups in alphabetical order:

* (w) Annotators Anonymous Open Group
* (p) CNN Restricted Group
* (w) Dinosaur Fans Open Group
* (w) Public
* (p) My Private Group One
* (p) My Private Group Two

Here `(w)` means the world icon, shown next to open groups and the public group, as it is currently. And `(p)` means the private group icon, shown next to private groups as it is currently and also next to the new restricted groups.

I understand that the icons will be changing and the world and public icons will be going away in future designs, but for this card we're just getting restricted groups working, we're not making any design changes.

**Comment by seanh** [comment]
@dawariley There's a lot of stuff in the design mockup you posted above, we aren't going to be able to implement that in one step. I think we'll have to break that mockup up into several intermediate mockups that we can implement and ship one by one. Each one of those intermediate design changes can be its own card, please, as each represents a significant, shippable chunk of work. I think you should work with a developer at some point to break it up into separate cards.

**Comment by seanh** [comment]
@ajpeddakotla 

> The top group is the default (scoped) group.
> If there is more than one scoped group on a domain, the groups are sorted alphabetically, agnostic of wether the groups are open or restricted groups (i.e. they'd be sorted alphabetically, interleaved)
> The publisher should be able to sort the groups in whichever way they desire and override the default settings determined by Hypothesis.

There's a few things that confuse me about this Arti:

1. We don't have any concept of a "default" group in Hypothesis currently. I'm not sure what you mean by that. Where is the default group defined? Who defines this? And how is the default group different from just the first group in the sort ordering of the groups?

2. _"The publisher should be able to sort the groups in whichever way they desire and override the default settings determined by Hypothesis."_ <- This is definitely a big, separate feature, and we already have a [separate card for group sort ordering features](https://github.com/hypothesis/product-backlog/issues/423). Can we figure out what the user stories are for sort ordering customization features, and write up each as a separate card?

For _this_ card I suggest we stick with what I've just suggested in [my comment above](https://github.com/hypothesis/product-backlog/issues/496#issuecomment-368849337) and note that I included _"If there is more than one scoped group on a domain, the groups are sorted alphabetically, agnostic of wether the groups are open or restricted groups (i.e. they'd be sorted alphabetically, interleaved)"_ in that.

**Comment by seanh** [comment]
Lets talk about this card in standup today...

**Comment by dawachan** [comment]
@seanh happy to break this mockup up, I might have questions about what exactly we are/not delivering against the mockup so that I can deliver against it. It would have been super useful to have looked at the original mock in the restricted groups discussion with the eng team or when I posted it in eng-general recently as I need consensus and input from the team about what will be delivered i.e. what is being exposed to the end user. let's sync on this and figure out the best way to get the input i need in order to be most effective in supporting the individual cards.

**Comment by dawachan** [comment]
@seanh I also have more general concerns about the effect on the UX of the new process we have adopted i.e shipping minimal functional units in each iteration. I am on board with this and believe it is an effective approach but, if we push it to prod and it is an interim UX, ie. it doesn't reflect the final UX which was thought through and considered holistically with all parts functioning whether this will confuse users with constantly changing design patterns and will be ultimately detrimental to their experience of H, as opposed to waiting until a more complete 'bundle' of UX that I'd be more happy with releasing. I think in the small scale we're rolling this out it isn't overly detrimental, but longer term I think this has to be considered as our user base continues to grow.

**Comment by seanh** [comment]
@dawariley Agree, there's definitely some stuff to think about there, and I don't think we've collectively figured out exactly how design fits into this iterations-based approach.

**Comment by dawachan** [comment]
yes I agree, something we definitely need to work out.

**Comment by seanh** [comment]
FWIW I absolutely _do_ want to get the mockup above into the product, I think it's a fantastic design that looks and works a million times better than what we have currently. We just have to figure out how to get there

**Comment by dawachan** [comment]
I have created a new card for adding the inclusion of group menu organization icons to the groups control #502 

This is an outcome of a proposal I made in conversation with @seanh about a better interim solution than what we have now and takes us one step closer to the target UX. It assumes removing the duplication of (w) and (p) icons outlined in @seanh comment above. Can be discussed in our design/dev sync meeting today.

**Comment by dawachan** [comment]
Yes, and the new issue I created #502 is a brave new step to get us there..

**Comment by seanh** [comment]
As discussed in product team meeting I've updated the description of this card to reflect the acceptance criteria we've all agreed on, including sort ordering. Now that confusion is cleared up, and we all know what we're doing, we can start making progress on delivering restricted groups!

**Comment by ajpeddakotla** [comment]
@seanh  to elaborate on this card, and tag any related subcards.

**Comment by seanh** [comment]
> <del>- [ ] if you're not logged into H, you only see these groups.</del>

@ajpeddakotla I've deleted this acceptance criteria for now, we can put it back if necessary, but I'm not sure what _you only see these groups_ means? The current implementation is that a not-logged-in user on a publisher's site would see any open and restricted groups that the publisher has, plus the Public group. For example here's what <https://biopub.hypothes.is/> (which is running the actual production code as it is currently) looks like right now when you're not logged in:

![2018-03-06-102812_2560x1440_scrot](https://user-images.githubusercontent.com/22498/37027462-3c7dcdb2-2129-11e8-9e10-c3629ffe1ccc.png)

**BioPub** is an open group and **BioPub Editors** is a restricted group.

Is there a requirement to remove the **Public** group when not logged in? And/or to remove open groups and leave only the restricted ones? If so that's doable of course but can I request a separate card?

**Comment by seanh** [comment]
I've checked off the acceptance criteria in the pr description above that are already done so far. The restricted groups implementation so far also has a bunch of bugs, I'll add a task list of things to fix to the pr desc above

**Comment by seanh** [comment]
I've checked the acceptance criteria for group sort ordering. There's a known issue that if you're a member of a restricted group you see the group twice in your menu, I've added a separate acceptance criteria to fix that. But apart from that bug I believe the group sort ordering on <https://biopub.hypothes.is/> is correct:

  1. All open groups and restricted groups are shown first, in alphabetical order (so different open and restricted groups will be interleaved with each other, if alphabetical ordering determines that)

  2. The _Public_ group is shown next, after the open and restricted groups

  3. All of the user's private groups are shown last, in alphabetical order

**Comment by ajpeddakotla** [comment]
Just a note that @seanh's earlier question was answered in standup. Acceptance criteria have been edited to reflect this.

**Comment by seanh** [comment]
@ajpeddakotla I think this was shipped

**Comment by ajpeddakotla** [comment]
Yup yup.... closing
