### ISSUE TITLE
GDPR - Implement encryption at-rest

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#559]
### Background
In order to meet GDPR requirements we need to determine which parts of the Hypothesis data cycle are unencrypted at rest, and work to encrypt those, in order to meet GDPR requirements. 

### Issues that need to be addressed 
1. Understand what data is current unecrypted at rest. Is it business critical?  Does it include personally identifiable information (PII)?
2. Implement systems to help set policies and control that data to meet compliance regulations when data is going outside of the organization (see GDPR principles of centralization, privacy by design and comprehensive security). https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/principles/

**Comment by jeremydean** [comment]
Just want to add that outside of GDPR, this is one of the basic questions asked on the security questionnaires I get from universities. For example:

https://docs.google.com/document/d/1Nivs37dph2X3vqefTfwWlOly9JZKbV5CwE1HRTAoTBM/edit?usp=sharing

**Comment by robertknight** [comment]
Assigned to me for elaboration/refinement.

**Comment by hmstepanek** [comment]
From the amazon docs: 
```
You can only enable encryption for an Amazon RDS DB instance when you create it, not after the DB
instance is created. However, because you can encrypt a copy of an unencrypted DB snapshot, you
can effectively add encryption to an unencrypted DB instance. That is, you can create a snapshot of
your DB instance, and then create an encrypted copy of that snapshot. You can then restore a DB
instance from the encrypted snapshot, and thus you have an encrypted copy of your original DB
instance. 
```
This means we have to copy our existing db to a new encrypted db. We could make this switch by either temporarily putting the app into readonly mode so no new annotations get added, or alternatively, we can write to both at once, then make the switch to the encrypted (there may be some missing data in between the copy and the writing to both but we can fix that by adding them after and since we are still using the old db to read at first, our customers will never know). <-The second approach is the same plan as we are using on ES so we may just want to keep both these the same.

Again, what's important in all of this is to make sure our backups work. We will want to make a backup of the encrypted db before we take down the old one. It sounds a bit complicated to restore an encrypted db from a non encrypted db so we should avoid that. Also we don't want non encrypted restores hanging around as that kinda defeats the purpose.

**Comment by hmstepanek** [comment]
The ES encryption is by domain so we will need to create a new domain in order to encrypt our es data. It might be easier to do this at the same time as we make a new cluster for the transition from es1.5 to es6.2.

**Comment by hmstepanek** [comment]
- [ ] Make new ES domain.
- [ ] Configure new ES to use encryption.
- [ ] Make an encrypted copy of our db.
- [ ] Add the ability to write to both db's in h.
- [ ] Add the ability to read from either the old or the new db in h.
- [ ] Delete the old DB.
- [ ] Cleanup tasks
- [ ] Verify backups work on encrypted db.
- [ ] Make an encryption key/keys for db and es. These can either be custom or generated through amazon.

Disclaimer: I have left out a lot of ES tasks as they will be the same as the ones we already have.

**Comment by robertknight** [comment]
Can I also add AWS encryption key management as something that needs to be looked into. We need to understand where keys are stored, how access to them is managed etc.

**Comment by hmstepanek** [comment]
Ah yes! Please do!

**Comment by hmstepanek** [comment]
General info about amazon's encryption:

> Amazon RDS encrypted instances use the industry standard AES-256 encryption algorithm to encrypt your data on the server that hosts your Amazon RDS instance. Once your data is encrypted, Amazon RDS handles authentication of access and decryption of your data transparently with a minimal impact on performance. You don't need to modify your database client applications to use encryption.

**Comment by seanh** [comment]
I've made three separate cards:

1. [Implement encryption-at-rest for Elasticsearch (Epic)](https://github.com/hypothesis/product-backlog/issues/562)
2. [Implement encryption-at-rest for PostgreSQL (Epic)](https://github.com/hypothesis/product-backlog/issues/621)
3. [Spike to find out what else (if anything) we need to implement encryption-at-rest for](https://github.com/hypothesis/product-backlog/issues/622)

Closing this card. I'll copy-paste Hannah's comment about implementing encryption-at-rest for Postgres onto the Postgres card.
