### ISSUE TITLE
EPIC: GDPR Work

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#564]
### Background: 
GDPR is a new set of European Union privacy laws that will be enforced in 60 days. ~~You can read more about the laws and requirements here: https://www.eugdpr.org/~~ (_See my comment below - robertknight_)

Hypothesis has undergone an external evaluation to determine the work that we as an organization need to do to meet GDPR requirements. This epic card tracks the seperate pieces of work. 

### Issues: 
- [x] Implement Encryption At Rest: #559
- [x] Ask users to opt-in to our privacy policy: #560
- [x] Logging - Track and Document: #563 
- [x] Implement Cookies Affirmative Consent Dialogue Box #574  
- [x] update privacy policy (tracked in Trello)

**Comment by ajpeddakotla** [comment]
Updated this to reflect that we no longer need to: 
- Implement Consent for Minors under the age of 16: #561 
because we will be changing the language in our policy instead. See comment from @rallos that addresses this here: https://github.com/hypothesis/product-backlog/issues/561#issuecomment-379343664

**Comment by robertknight** [comment]
> You can read more about the laws and requirements here: https://www.eugdpr.org/

I note that this site is run and paid for by [Trunomi](http://www.trunomi.com), who sell "customer consent and data rights management technology".

A hopefully more neutral resource is the UK's Information Commissioner's Office: https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/

**Comment by robertknight** [comment]
From what I understand of what I've read so far about GDPR, we'll need to clearly document some aspects of how we comply (eg. which lawful basis we use for processing any data). Is there an existing issue that covers updates to the privacy policy? That should be added above.

**Comment by rallos** [comment]
The lawful basis for which you process any data is "Necessary for the
Performance of a Contract"

**Comment by robertknight** [comment]
Our database, search index and backup storage is now encrypted. For any customers who need that particular box ticked, we can now tick it.
