### ISSUE TITLE
GDPR: Implement Privacy Policy Opt-in on User Signup

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#591]
![image](https://user-images.githubusercontent.com/439947/39054103-bdc2d8ea-447e-11e8-8224-a85da444b68b.png)

## Justification

In order to meet new GDPR requirements, we need to provide users with a link to the privacy policy on the sign up form and include a way to actively opt-in to our privacy policy. Additional text in the prompt will link users to terms of service and community guidelines.

We are required to persist data about the user's opt-in to the privacy policy. We do not need to persist the agreement to other documents or terms.

## Scope

This task applies to the signup process via the standard web form and the persistence of opt-in data for the privacy policy, for new users.

### Out of Scope

* Gathering consent for any other user-creation process besides the web signup form (e.g. the API for creating a user)
* Persistence or munging of any data beyond the single agreement-to-privacy-policy data point
* Marketing (email) opt-in (this is currently tracked in https://github.com/hypothesis/product-backlog/issues/431). This was previously conflated into this task so I call it out explicitly here.
* Updating or obtaining consent for existing users

## Acceptance Criteria

* [x] The User model and underlying database schema should be updated to persist datetime/timestamp information about when the user (last) agreed to the privacy policy.
* [ ] A checkbox should be added to the user signup form (tracked in https://github.com/hypothesis/product-backlog/issues/611)
    * [ ] Text in the checkbox description should be linked to the three documents referenced, which are at 
        * https://web.hypothes.is/privacy/
        * https://web.hypothes.is/terms-of-service/
        * https://web.hypothes.is/community-guidelines/
    * [ ] The checkbox should be _unchecked_ by default—requiring user action
    * [ ] If users do not accept the privacy policy (i.e. check the checkbox), an error (likely in the form of a tooltip) is displayed with the text "Acceptance of the privacy policy is required." Styling should be consistent with tooltip styling as shown in screen shot below.
* [ ] Creation of the new User should include setting the new privacy policy field to the datetime of the signup

![screen shot 2018-04-20 at 15 12 25](https://user-images.githubusercontent.com/5212631/39055990-69b87460-44ad-11e8-90d6-78b7114701e4.png)

## Considerations

* A DateTime type of field seems useful for the new user field as it could allow us to update the privacy policy over time and have data about when the user last agreed to one.
* I had had some concerns about the API endpoint we have for creating a user and whether this was also subject to these privacy-policy-opt-in requirements. From a conversation in Slack, @robertknight said:

> The GDPR defines two kinds of parties who get involved with the processing of data, a “data controller” and a “data processor”. The “data controller” is as I understand it, the party that the user directly interacts with, which may in turn delegate various work to data processors.

> In this context, I believe Hypothesis would be a data processor and a publisher using the API would be the data controller.

> In that case, we do have certain responsibilities as a data processor, but collecting consent from the user to send personal data to us is the task of the controller.

Because of this, it seems ideal to keep the logic for setting the privacy-policy-agreement field closer to the UI layer. Translation: we should not set the value of this field automatically when creating a new user object—it should be set explicitly, probably by the view (but I'll leave that up to whoever picks this up!).

**Comment by dawariley** [comment]
_Style of tooltip below: (copied from #560)_

![screen shot 2018-04-20 at 15 12 25](https://user-images.githubusercontent.com/5212631/39055990-69b87460-44ad-11e8-90d6-78b7114701e4.png)
