### ISSUE TITLE
LMS Users and Groups should be Automatically Provisioned

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#597]
### User Stories: 
**Authentication:** 
- [x] Students using Canvas should be provisioned and authenticated into Hypothesis #593
- [x] Instructors using Canvas should be provisioned and authenticated into Hypothesis #594

**Groups:** 
- [x] LMS Student Users should automatically be members of their course's private group #595
- [x] Private Groups for each LMS Course should be created as needed for assignments #596 
- [x] Appropriate Course Private Group should be focused in client for LMS users #680

**Comment by seanh** [comment]
@lyzadanger Can we close this now?

**Comment by lyzadanger** [comment]
Wahoo!
