### ISSUE TITLE
Elasticsearch upgrade cleanup tasks

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#608]
Once h is switched over to using the new Elasticsearch cluster in production, there are a bunch of cleanup tasks that need to be done to remove obsolete code, take down the old cluster and update documentation:

**h**
- [x] Remove code that supports indexing / searching ES1
- [x] Remove ES1 `es_client` and `request.es` fixtures
- [x] Rename get_es6_client => get_client (5213)
- [x] Remove feature flags related to the ES upgrade
- [x] Remove the ES 1.x container from docker-compose (5213)
- [x] Delete old tests (e.g. `old_*.py` files etc) - https://github.com/hypothesis/h/issues/5143 (Rob)
- [x] Remove any of the elasticsearch_dsl code that we are no longer using (https://github.com/hypothesis/h/pull/5271)
- [x] Rename everything with es6 to es (5213)
- [x] Remove es6 flag in `search reindex` CLI command
- [x] Change port of es (https://github.com/hypothesis/h/pull/5215)
- [x] Change port of es in bouncer (https://github.com/hypothesis/bouncer/pull/138)

**Operations**
- [x] Remove the old environment vars for es1.
- [x] Take down the ES 1.x cluster in AWS
- [x] Remove any old unencrypted backups of ES 1.x data that we no longer need in S3
- [x] Update playbook documentation that refers to Elasticsearch (Rob - https://github.com/hypothesis/playbook/pull/180)
- [x] Update any ansible scripts in the playbook that refer to Elasticsearch
- [x] Remove any monitoring scripts which are specific to the ES 1 cluster

**Refactoring / other code cleanup**
- [x] Ignore unknown query parameters to `/api/search` - https://github.com/hypothesis/product-backlog/issues/741
- [x] Review search code, identify any additional cleanup / refactoring required (I think we've done enough iteration on this code for now - _robertknight_)
- [x] Replace Builder class w/ elasticsearch-dsl (https://github.com/hypothesis/product-backlog/issues/746)

**Comment by robertknight** [comment]
I updated the description to separate out tasks in h vs operations. I also removed the sections on dependabot and ES update notifications to limit the scope of this issue.

I will add a task to talk about future ES upgrade strategy though.

**Comment by hmstepanek** [comment]
@ajpeddakotla @robertknight The last remaining issue (future es upgrade plan) is on the sprint board in to discuss so I think we can probably close this card as it's not tracking anything new?

**Comment by robertknight** [comment]
Agreed. I removed that card from this issue.
