### ISSUE TITLE
Make client experience smooth and seamless when in "LMS Mode"

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#789]
The client in "LMS mode" has a few differences from "normal mode" operation. When using the client in LMS mode, an instructor or student should not encounter elements that don't make sense or don't work.

The following are notes from @seanh :

Client fixups that I know are gonna need to be done when it's in LMS mode...

• Hide leave group buttons on groups menu
• Hide bouncer links wherever they appear in the client (they're used in various places in the client, not just on the annotation cards, and none of them can work in LMS) (_They only appear in the action buttons for annotation cards. The share link is already hidden in this context - robertknight_)

Things that already change for free:

• Display names are used
• Log out button is gone
• I think links to group's activity pages are already hidden (_They are - robertknight_)
• I think links to the "individual pages" for annotations are already hidden too (_They are - robertknight_)

----

**Comment by robertknight** [comment]
You can test this out now in production by using assignments on the "Hypothesis 101" course that seanh created, for example: https://hypothesis.instructure.com/courses/4/assignments/363?module_item_id=544

From a quick test just now, I see the following items which definitely need to be addressed:

- [x] There is a "Leave group" button in the groups drop-down menu. If you click that, the menu ends up in a slightly nonsensical state where there are no groups in the dropdown list but annotations are still shown. If you reload the page, you get rejoined to the group again, so leaving is not fatal. - https://github.com/hypothesis/product-backlog/issues/841
- [x] Annotations have share links, but they don't work because they point to the _Via_ URL and the annotations only work when the user visits the top-level URL which can pass the LMS user and group context to the client. https://github.com/hypothesis/product-backlog/issues/843
- [x] The sidebar tutorial describes how to share an annotation. Depending on how we address the bouncer link issue we'll have to remove or change that. My inclination would be to simplify the instructions as much as possible to fit the context. https://github.com/hypothesis/product-backlog/issues/842
- [x] The sidebar tutorial describes how to create a private group. This is not possible. https://github.com/hypothesis/product-backlog/issues/842

On top of that some other items that I see for discussion:

- [ ] Given the use case, do we still want to support private annotations? I see a possibility that the user may post private annotations by mistake. This is compounded by the fact that the private/public state is "sticky". We could leave this as-is pending feedback.
- [ ] Do we want to keep, remove or change the sidebar tutorial that shows up for newly created user accounts in this context? See https://github.com/hypothesis/product-backlog/issues/842
- [ ] Do we need to change any of the links in the "Help" panel to be appropriate to the LMS context. Currently we have our standard links for reporting support issues and accessing our KB.

I notice that the document share link is already hidden in this context, which I wasn't expecting but makes sense.

The list of essential items that I listed above seems quite small, which is good. It looks like we already addressed most of the potential issues in the context of eLife, since activity pages are not yet supported for third party authorities.

**Comment by robertknight** [comment]
I've filed issues for things that are obviously broken/wrong in the LMS context. I expect there will be additional wishlist feedback once various parties (Jeremy, Dave, Katelyn) have spent some time testing account provisioning and processing feedback from users. Based on my recollections of discussions with Sean a few weeks ago I think that is outside the scope of this issue however.

**Comment by lyzadanger** [comment]
I'm going to reopen this issue and treat it as an epic for now (with re-wording of title)—an umbrella issue for making the client usable in the "LMS mode" per provisioning.

**Comment by seanh** [comment]
@lyzadanger I think this is now done?
