### ISSUE TITLE
Improve groups selector UX

### ISSUE THREAD

**Issue by dwolfe** [hypothesis/product-backlog#848]
Part of https://github.com/hypothesis/product-backlog/issues/866

### Problem/Background
When we open up groups to be shared and appear on sites they aren't scoped to, the presentation of these groups in the groups menu will need updating, so that users can have a better understanding of the groups they are actually seeing, why they are seeing them, and what groups they are actually a member of. 

_Spun off from https://github.com/hypothesis/lms/issues/294 - see comments there for context._

In preparation for supporting unscoped restricted groups, (and eventually multi-service), we'll need to revisit how we handle that complexity while allowing users to change their viewing context.

### User Story
As a user, I'd like to be able to follow a link to a group and view annotations made in that group, on a specific document, and see the group appear in my group scope dropdown on the sidebar. If I am a member of that group, I expect that group to appear on my groups list. If I am not a member of that group, I expect that group to appear as part of a seperate "featured" list (terminology TBD). 

### Acceptance Criteria
- [x] Users should know their current viewing context (which set of annotations are being displayed) at all times
- [x] Users should be able to easily change viewing context (known groups should be findable, etc.)
- [x] Users should be able to understand the differences between the contexts available to them (ie. groups they belong to, groups that are read-only for them, groups they can contribute to, groups that are provided/managed by the host site, etc.)

**Comment by dwhly** [comment]
Thanks @dwolfe.  Linking to a bit of work that was done previously around some of these questions, in particular signaling to users that a group (for them) might be read only, etc.  

I don't believe it was ever implemented.
https://github.com/hypothesis/product-backlog/issues/552  

PS You'll note on closer inspection that the mockups are inconsistent about whether the `READ ONLY` badge is inside the caret or outside.  A point about which there was a ridiculous amount of discussion! :)

Also, there's some discussion around changes to the adder in this issue:
https://github.com/hypothesis/product-backlog/issues/489

And then ultimately this issue:
https://github.com/hypothesis/product-backlog/issues/575

**Comment by dwolfe** [comment]
This issue also dovetails with the QDR work: https://github.com/hypothesis/product-backlog/issues/844

I had QDR in mind when I created this issue, since solving for sharing unscoped groups has implications for the group selector, but this should be helpful beyond QDR's needs. Thankfully, the backend work being done for QDR will enable some of the features discussed in the issues @dwhly referenced above, but this ticket will address only the group selector menu. (We can use the already existing issues to tackle the read-only features.)

**Comment by robertknight** [comment]
This issue has been superseded by subsequent discussions and design iterations. The latest iteration is a combination of the mocks in [this issue](https://github.com/hypothesis/product-backlog/issues/974) and the introduction of "My groups", "Featured groups" and "Currently viewing" sections in the groups menu that were introduced earlier:

<img width="354" alt="Screenshot 2019-06-13 12 10 00" src="https://user-images.githubusercontent.com/2458/59428136-60e95b80-8dd4-11e9-9887-3e80d3c3c1c3.png">

The remaining work to get this shipped is tracked in other tasks.

**Comment by robertknight** [comment]
Actually, on second thoughts I'll leave this open until we have actually shipped it.
