### ISSUE TITLE
Add option for world-readable groups to be available outside of their defined scopes in certain cases

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#865]
Part of https://github.com/hypothesis/product-backlog/issues/866

As a publisher, I want to be able to decide whether a given restricted group I control should be visible (and allow annotation) for members outside of its defined scopes, such that I am able to control where my group’s members may annotate.

As a member of a restricted group that my publisher has allowed to be annotated outside of its scope, I want that restricted group to show up in my list of available groups in the clients everywhere on the web, so I may annotate in that group anywhere—not just within the group's scopes.

-----

For the work outlined in https://github.com/hypothesis/product-backlog/issues/864 to happen, it has to be possible to get annotations into world-readable groups outside of their scopes. Thus:

- [x] There should be some way to configure a world-readable group (open, restricted) such that it may contain annotations for documents that fall outside of its defined scope(s).
- [x] This configuration option should default to "nope/off" so that we don't disrupt the way that existing world-readable groups are working.
- [x] Restricted groups that are configured to be available outside of their scopes should appear in the client for members of those groups anywhere on the web, not just within their scope(s).
- [x] Restricted groups will continue to appear for users who are _not_ members of those groups as they do now: only within their defined scope(s)
- [x] Open groups will continue to appear for all users as they do now: only within their defined scope(s)
- [x] The API will accept annotations for documents outside of defined scope(s) for open and restricted groups so configured (this is currently disallowed).

### This work includes

- [x] Adding some form of configuration option for an open or restricted group to allow it to accept annotations and show up in the client for its members outside of its defined scope(s)
- [x] Removing the current API scope constraint for creating annotations for such groups (i.e. right now the API will not allow a user to create an annotation in an open or restricted group for a document outside of its scope(s))
- [x] Updating the groups API response such that appropriately-configured restricted groups are returned for their members web-wide, not just within their defined scope(s)
~~- [ ] Implementing UX improvements to help users understand the groups they're seeing available in the client.~~ (This is being tracked elsewhere)

#### Out of scope/tracked elsewhere

* Removing the requirement that world-readable groups have scope(s) defined for them. This may well be viable, it's just outside of this body of work as it's orthogonal.
* Figuring out how we allow people using the client to add annotations into  appropriately-configured _open_ groups outside of their scopes. The API will allow it, but it's unclear how we'd make this work in the client at present.

**Comment by lyzadanger** [comment]
Back-end/services work complete on this task!

**Comment by lyzadanger** [comment]
Yay!

**Comment by adam3smith** [comment]
Sorry to bother everyone -- this will be the last one I think: How can we designate a group as community group?

**Comment by klemay** [comment]
Hi @adam3smith! This feature is still in development— this issue was closed out as _part_ of the necessary work to get it working.
