### ISSUE TITLE
(EPIC) Implement ACL lists for our new groups model

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#89]
Based on the research work that @chdorner has done in the Spike and written about [here](https://github.com/hypothesis/product-backlog/issues/39), we're now working to implement access control lists for our new groups model. This issue tracks that work. 

# New group table columns

- `authority`
  - type: `string`
  - default: `"hypothes.is"`
- `readable_by`
  - type: `string`
  - possible values: `(NULL, "authority", "members", "world")`
- `writeable_by`
  - type: `string`
  - possible values: `(NULL, "authority", "members", "world")`
- `joinable_by`
  - type: `string`
  - possible values: `(NULL, "authority", "members", "world")`

### Issues in this epic: 
- [x] Implement group join permissions #93
- [x] API response renders read permissions correctly #97 
- [x] Restrict access to annotation when loading by through API id #96 
- [x] API search should only return readable annotations #95 
- [x] API response renders read permissions correctly #97
