### ISSUE TITLE
Enable deletion of user's w/ private groups w/ other user's annotations

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#909]
Problem: We currently have 2 user's who's accounts can't be deleted until we implement a way to delete a creator from a private group that has annotations made by other users. See [issue](https://github.com/hypothesis/private-issues/issues/21).

Proposed Solution:  

- [x] Set the creator as None if there are annotations by other's in the group, otherwise delete the group.
- [ ] Enable editing of private groups in the admin panel.
- [ ] Enable editing of group creator in the admin panel.
See [decision](https://github.com/hypothesis/product-backlog/issues/815).

**Comment by ajpeddakotla** [comment]
This is completed, right @hmstepanek? I believe we can close this.

**Comment by hmstepanek** [comment]
This is a 3 parter. The first part is done but the two other parts still remain.

**Comment by klemay** [comment]
We are now able to delete a user's account if they have created private groups where others have annotated. The creator of that group is set to "None" and other members continue to be able to annotate in the group. 

The problem initially presented in this ticket is solved. 

The two outstanding items in the checklist at the top of this issue (Enable editing of private groups in the admin panel; Enable editing of group creator in the admin panel) are nice-to-have items that I don't see us working on any time soon. 

@hmstepanek would you be ok with closing this issue? If we decide to implement those other checklist items down the road, we can create dedicated issues.

**Comment by hmstepanek** [comment]
@klemay Sounds good to me.
