### ISSUE TITLE
Version our API; Release 1.0

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#940]
We've reached consensus that we need to version our API (not too controversial!). The main objective is to get our current API to 1.0 so that we can start working on 2.x (breaking changes). General resolutions:

* We'll version 1.0 as soon as possible. There isn't any feature or improvement work slated for 1.0 at this time, though a few additive or refactor elements may make it into 1.0 before we cut the version. There will be no breaking changes between now and 1.0 "release."
* The "release" of version 1.0 effectively means "when we have systems and patterns in place to be able to differentiate API services between 1.0 and not-1.0."
* We've decided to version based on (Accept) Content Header negotiation, [a pattern supported by Pyramid innately](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/viewconfig.html#accept-content-negotiation).
* Version 1.0 will remain the default version of the API for some time. It will be used if client requests lack an Accept header or if the Accept header specifies version 1.0. We will request that users of the API start sending explicit Accept headers ASAP. Version 2.0, when it starts becoming available, will be available only if a client sends an Accept header "asking" for it.
* We're considering a "brownout" approach for deprecating 1.0, when we get to that point, in which we'll selectively make a given endpoint return a verbose error message for a short period of time to let clients know that the service will go away. This is a ways out yet.
* The above versioning strategy mirrors that of [GitHub's V3 REST API](https://developer.github.com/v3/#current-version), which is (editor's opinion) a well-designed API.

Some known tasks, which will likely be tracked separately as we go:

* [x] Pyramid config for view matching on Accept/Content Header negotiation
*  [x] Code organization within Pyramid app for versioning (emphasis on taking a light touch on this so we don't hobble ourselves)
* [x] Documentation bifurcation (there are several outstanding needs for documentation refactor, but let's not let that hobble us, either)
* [ ] Communication to existing API users

**Comment by lyzadanger** [comment]
Done!
